# Netlify Configuration
# This file configures how Netlify builds and serves your site

[build]
  # Directory with serverless functions
  functions = "backend/functions"
  # Directory to publish (your site root)
  publish = "."

[dev]
  # Local development port
  port = 3001
  # Auto-open browser
  autoLaunch = false
  # Directory to serve
  publish = "."

# Redirect API calls to functions (excluding maps which use proxy)
[[redirects]]
  from = "/api/calculate-price"
  to = "/.netlify/functions/calculate-price"
  status = 200

[[redirects]]
  from = "/api/create-booking"
  to = "/.netlify/functions/create-booking"
  status = 200

[[redirects]]
  from = "/api/create-payment-intent"
  to = "/.netlify/functions/create-payment-intent"
  status = 200

[[redirects]]
  from = "/api/confirm-payment"
  to = "/.netlify/functions/confirm-payment"
  status = 200

[[redirects]]
  from = "/api/track-flight"
  to = "/.netlify/functions/track-flight"
  status = 200

# Redirect root to indexMVP.html
[[redirects]]
  from = "/"
  to = "/indexMVP.html"
  status = 200

# Allow all static assets to be served directly
[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200

# Catch-all redirect for SPA (only for paths without extensions)
[[redirects]]
  from = "/*"
  to = "/indexMVP.html"
  status = 200

# Headers for JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables (template - actual values in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"

# Function configuration
[functions]
  # Directory for functions (using backend/functions as defined in build section)
  # directory = "backend/functions"  # Commented out as it's already defined in [build]
  # Node bundler for functions
  node_bundler = "esbuild"