/**
 * Household domain: variable definitions. scope says whether one value
 * belongs to the whole system or to one person. Values start unknown.
 */
import type { VariableDefinition } from "@/model/domain";
import { INPUT_IDS as I, OTHER_KEYS as O } from "./keys";

export const HOUSEHOLD_VARIABLES: VariableDefinition[] = [
  // ---- system scope: household money ----
  { key: I.essentialExpenses, name: "Essential monthly expenses", description: "Rent, food, utilities, transport, insurance, childcare.", unit: "$/month", category: "structure", changeSpeed: "slow", scope: "system", targetMode: "at_most", referenceRange: { min: 0, max: 6000 }, question: "What are the essential monthly expenses (rent, food, utilities, transport, insurance, childcare)?" },
  { key: I.discretionaryExpenses, name: "Discretionary monthly expenses", description: "Spending that could be cut first in a crisis.", unit: "$/month", category: "event", changeSpeed: "fast", scope: "system", targetMode: "at_most", referenceRange: { min: 0, max: 1500 }, question: "Roughly how much is spent each month beyond the essentials?" },
  { key: I.liquidReserves, name: "Liquid reserves", description: "Cash and balances available within days.", unit: "$", category: "buffer", changeSpeed: "slow", scope: "system", targetMode: "at_least", referenceRange: { min: 0, max: 20000 }, question: "How much money is available within days (checking, savings, cash)?" },
  { key: I.totalDebt, name: "Total debt", description: "All outstanding balances.", unit: "$", category: "structure", changeSpeed: "slow", scope: "system", targetMode: "at_most", referenceRange: { min: 0, max: 20000 }, question: "What is the total outstanding debt?" },
  { key: I.monthlyDebtPayments, name: "Monthly debt payments", description: "Minimum payments due each month.", unit: "$/month", category: "structure", changeSpeed: "slow", scope: "system", targetMode: "at_most", referenceRange: { min: 0, max: 1000 }, question: "What are the minimum debt payments due each month?" },
  { key: I.productiveAssets, name: "Productive assets", description: "Equipment or capital that earns or saves money.", unit: "$", category: "asset", changeSpeed: "slow", scope: "system", targetMode: "at_least", referenceRange: { min: 0, max: 10000 }, question: "What equipment, tools or capital currently earn or save money, and roughly what would they cost to replace?" },
  { key: I.capitalConversionRate, name: "Capital conversion rate", description: "Share of surplus that becomes reserves or productive assets.", unit: "share 0-1", category: "agency", changeSpeed: "slow", scope: "system", targetMode: "at_least", referenceRange: { min: 0, max: 1 }, question: "In months with money left over, roughly what share was kept as savings or spent on something that earns?" },
  { key: I.annualReturnRate, name: "Return on existing capital", description: "Annual return assumed on productive assets (an estimate).", unit: "rate/year", category: "structure", changeSpeed: "slow", scope: "system", targetMode: "exact", referenceRange: { min: 0, max: 0.1 } },
  { key: I.switchingCost, name: "Switching cost", description: "Career-capital points lost per change of path (an estimate that sets a model scale).", unit: "index points/switch", category: "structure", changeSpeed: "slow", scope: "system", targetMode: "exact", referenceRange: { min: 0, max: 20 } },
  { key: I.effortToCapitalRate, name: "Effort-to-capital rate", description: "Index points gained per focused, persistent protected hour (an estimate that sets the scale of the index).", unit: "index points/hour", category: "structure", changeSpeed: "slow", scope: "system", targetMode: "exact", referenceRange: { min: 0, max: 0.5 } },
  { key: O.financialPressure, name: "Financial pressure", description: "Felt pressure about money, self-rated 0-10, for the household.", unit: "self-rating 0-10", category: "event", changeSpeed: "fast", scope: "system", targetMode: "at_most", referenceRange: { min: 0, max: 10 }, question: "On a 0-10 scale, how much does money feel like a pressure right now, and what most recently drove it up or down?" },
  { key: O.planningHorizon, name: "Planning horizon", description: "How far ahead money decisions are actually made.", unit: "months", category: "structure", changeSpeed: "slow", scope: "system", targetMode: "at_least", referenceRange: { min: 0, max: 12 }, question: "When a money decision comes up, how far ahead is it actually planned: the next paycheck, the next few months, or the next year?" },
  { key: O.singleVehicleDependency, name: "Single-vehicle dependency", description: "Several incomes require one vehicle (1 = yes, 0 = no).", unit: "flag 0/1", category: "dependency", changeSpeed: "slow", scope: "system", targetMode: "at_most", referenceRange: { min: 0, max: 1 }, question: "Do several incomes depend on one vehicle, one location, or one person's availability?" },
  { key: O.vehicleRepairExposure, name: "Vehicle repair exposure", description: "Plausible one-off repair cost in the next year.", unit: "$", category: "shock", changeSpeed: "fast", scope: "system", targetMode: "exact", referenceRange: { min: 0, max: 5000 } },
  { key: O.riskTolerance, name: "Risk tolerance", description: "Preference for predictable income over upside, for the household.", unit: "index 0-1", category: "person_fit", changeSpeed: "slow", scope: "system", targetMode: "exact", referenceRange: { min: 0, max: 1 } },
  { key: O.supportNetwork, name: "Support network", description: "People and arrangements that could help with money, housing, childcare or work leads.", unit: "index 0-1", category: "buffer", changeSpeed: "slow", scope: "system", targetMode: "at_least", referenceRange: { min: 0, max: 1 }, question: "If income stopped for two months, who could realistically help with money, housing, childcare or work leads?" },
  { key: O.careLoad, name: "Care load", description: "How much the household's time goes to dependants.", unit: "index 0-1", category: "constraint", changeSpeed: "slow", scope: "system", targetMode: "at_most", referenceRange: { min: 0, max: 1 }, question: "How many people depend on the household for care or money, and how many hours a week does that take?" },
  // ---- member scope: one person's capacity, agency and fit ----
  { key: I.careerCapital, name: "Career capital (index)", description: "Skills, credentials, reputation and relationships that raise the income this person can command. An unscaled 0-100 judgment.", unit: "index 0-100", category: "asset", changeSpeed: "slow", scope: "member", targetMode: "at_least", referenceRange: { min: 0, max: 100 }, question: "Which credentials, skills or relationships currently raise the income this person can command?" },
  { key: I.protectedHours, name: "Protected compounding hours", description: "Weekly hours this person reliably reserves for skill-building.", unit: "hours/week", category: "asset", changeSpeed: "slow", scope: "member", targetMode: "at_least", referenceRange: { min: 0, max: 20 }, question: "In a typical week, how many hours does this person reliably reserve for building skills rather than sell for immediate income?" },
  { key: I.majorPaths, name: "Simultaneous major paths", description: "Number of big directions this person pursues at once.", unit: "count", category: "agency", changeSpeed: "slow", scope: "member", targetMode: "at_most", referenceRange: { min: 0, max: 5 }, question: "How many major directions (jobs, courses, businesses) is this person pursuing at the same time?" },
  { key: I.switchingFrequency, name: "Switching frequency", description: "How often this person's main path changes.", unit: "switches/year", category: "agency", changeSpeed: "slow", scope: "member", targetMode: "at_most", referenceRange: { min: 0, max: 4 }, question: "In the last 24 months, how many times did this person's main path change?" },
  { key: I.qualityOfEffort, name: "Quality of effort", description: "How focused this person's protected hours are (a self-rating).", unit: "index 0-1", category: "agency", changeSpeed: "slow", scope: "member", targetMode: "at_least", referenceRange: { min: 0, max: 1 }, question: "During protected hours, how focused is the work (interruptions, clear goals, feedback)?" },
  { key: I.persistence, name: "Persistence", description: "Tendency to keep going on a chosen path (a judgment, never inferred from one event).", unit: "index 0-1", category: "agency", changeSpeed: "slow", scope: "member", targetMode: "at_least", referenceRange: { min: 0, max: 1 }, question: "In the last 24 months, which career or business paths received at least 100 hours of sustained work?" },
  { key: O.survivalWorkShare, name: "Survival-work allocation", description: "Share of this person's working hours sold for immediate cash rather than invested in capacity.", unit: "share 0-1", category: "structure", changeSpeed: "slow", scope: "member", targetMode: "at_most", referenceRange: { min: 0, max: 1 } },
  { key: O.availableNewHours, name: "Hours available for anything new", description: "After work, commuting, care and sleep.", unit: "hours/week", category: "constraint", changeSpeed: "slow", scope: "member", targetMode: "exact", referenceRange: { min: 0, max: 30 }, question: "After work, commuting, care and sleep, how many hours a week are genuinely free for something new?" },
  { key: O.scheduleFlexibility, name: "Schedule flexibility", description: "How freely this person's working hours can be moved.", unit: "index 0-1", category: "person_fit", changeSpeed: "slow", scope: "member", targetMode: "exact", referenceRange: { min: 0, max: 1 }, question: "How freely can working hours be moved (fixed shifts, school pickups, care duties)?" },
  { key: O.physicalCapacity, name: "Physical capacity", description: "Whether physical limits rule out or restrict kinds of work (stated, never diagnosed).", unit: "index 0-1", category: "person_fit", changeSpeed: "slow", scope: "member", targetMode: "exact", referenceRange: { min: 0, max: 1 }, question: "Are there physical limits (lifting, standing, driving hours, health conditions) that rule out or restrict certain kinds of work?" },
  { key: O.retrainingReadiness, name: "Retraining readiness", description: "What retraining or job change this person would actually take on within a year.", unit: "index 0-1", category: "agency", changeSpeed: "slow", scope: "member", targetMode: "at_least", referenceRange: { min: 0, max: 1 }, question: "If the current work disappeared, what retraining or job change would this person actually be willing and able to take on within a year?" },
];

export const HOUSEHOLD_VARIABLE_BY_KEY: Record<string, VariableDefinition> = Object.fromEntries(
  HOUSEHOLD_VARIABLES.map((v) => [v.key, v]),
);
