-- ============================================================
-- Migration 019 — PR-T: pickup-time integrity (plan v8.6 §3E)
--
-- GENERATED by database/migrations/tools/prt-guard-transform.js from the
-- migration-018 writer bodies. Do not hand-edit: regenerate, and the
-- executed suite (tests/prt-pickup-integrity.test.js) asserts byte-equality.
--
-- WHAT THIS DOES
--   * adds public.linkmia_pickup_is_future(TIMESTAMPTZ, TIMESTAMPTZ) — the
--     comparator, IMMUTABLE STRICT, security invoker, client roles denied;
--   * accept_quote_create / accept_quote_edit: every genuinely NEW write
--     requires the submitted/proposed pickup to be strictly future —
--     checked before mutation on the transaction-stable clock, and again as
--     the LAST blocking statement of the inner subtransaction on the live
--     clock (SQLSTATE ZQ019 -> every write rolls back -> outcome
--     pickup_time_elapsed). Receipt-first replay ordering is preserved: an
--     exact retry lands on its receipt before any clock is consulted.
--
-- WHAT THIS DOES NOT DO
--   * no table, column, index, constraint, trigger or RLS change; NO grant
--     change to the EXISTING writers (identity/owner/ACL/config are verified
--     equal to the pre-capture). The NEW helper is the one ACL event: it
--     receives a RESTRICTED ACL — EXECUTE for the captured writer owner(s)
--     only; PUBLIC, anon, authenticated, service_role and every other grantee
--     revoked, and the exact grantee set verified;
--   * the quote_verifications verdict CHECK is untouched — the GUARD records
--     NO verdict row (no verdict named pickup_time_elapsed exists). The edit
--     writer's pre-existing operationId-less 'no_request_id' instrument
--     (off/observe, written before the guard) is unchanged and pinned, not
--     moved; ZQ017 is not reused;
--   * signatures are IDENTICAL (true in-place replacement);
--   * no minimum lead time; fares, tokens, cancellation and driver-status
--     semantics are unchanged; accept_optional_edit is untouched.
--
-- FINGERPRINT GATE: the pre-capture refuses to run unless BOTH installed
-- writer bodies are EXACTLY the reviewed 018 bodies (sha256 of
-- pg_proc.prosrc — the values below, generated from the reviewed 018 text and
-- printed by preflight A2). Any other body — an unnoticed hotfix, a manual
-- edit — aborts the whole transaction before anything is touched. After
-- replacement, the installed bodies must equal this artifact's own bodies.
--
-- RUN VIA docs/PRT-MIGRATION-RUNBOOK.md ONLY. Emergency rollback:
-- database/migrations/018_r1_rollback.sql — restores the migration-017
-- DURATION BEHAVIOR (the verified-duration requirement returns) PLUS the PR-T
-- pickup guard; self-contained (creates the helper first).
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- PRE-CAPTURE: exact namespace-qualified identities, owners, ACLs AND BODY
-- FINGERPRINTS (sha256 of pg_proc.prosrc) of both writers BEFORE replacement
-- (regprocedure resolution is itself fail-closed). The precheck REFUSES to
-- proceed unless each installed body is a recognized reviewed body — an
-- unnoticed production change is never overwritten.
-- ------------------------------------------------------------
CREATE TEMP TABLE prt_pre_state ON COMMIT DROP AS
SELECT p.oid, p.proname, p.proowner, p.proacl, p.proconfig,
       encode(extensions.digest(p.prosrc, 'sha256'), 'hex') AS body_fp
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'public'
  AND p.oid IN ('public.accept_quote_create(uuid,uuid,uuid,text,text,uuid,text,jsonb,numeric,text,text,text,jsonb)'::regprocedure,
                'public.accept_quote_edit(uuid,uuid,uuid,text,uuid,integer,text,uuid,text,jsonb,numeric,text,text,text,jsonb)'::regprocedure);

DO $prt_precheck$
DECLARE
  v_row RECORD;
  v_accepted TEXT[];
BEGIN
  IF (SELECT count(*) FROM prt_pre_state) <> 2 THEN
    RAISE EXCEPTION 'PR-T: expected exactly the two public writers before replacement';
  END IF;
  FOR v_row IN SELECT * FROM prt_pre_state LOOP
    v_accepted := CASE v_row.proname
      WHEN 'accept_quote_create' THEN ARRAY['ed86cca5e4f5046dc9503771a38bb63f7b4140956dfb94b645f076cd59483388']::TEXT[]
      ELSE ARRAY['cc56cc673236db967d738209c9f9d5423e0e7117a74358e48280c08f0cd14b41']::TEXT[] END;
    IF NOT (v_row.body_fp = ANY (v_accepted)) THEN
      RAISE EXCEPTION 'PR-T: installed % body fingerprint % is not a recognized reviewed body (accepted: %) — an unreviewed change is installed; refusing to overwrite it',
        v_row.proname, v_row.body_fp, v_accepted;
    END IF;
    IF has_function_privilege('anon', v_row.oid, 'EXECUTE')
       OR has_function_privilege('authenticated', v_row.oid, 'EXECUTE') THEN
      RAISE EXCEPTION 'PR-T: client role holds EXECUTE on % — refuse over privilege drift', v_row.proname;
    END IF;
    IF NOT has_function_privilege('service_role', v_row.oid, 'EXECUTE') THEN
      RAISE EXCEPTION 'PR-T: service_role lacks EXECUTE on % — refuse over privilege drift', v_row.proname;
    END IF;
  END LOOP;
END;
$prt_precheck$;

-- The comparator, as ONE named IMMUTABLE STRICT SQL function so the exact
-- boundary is observable: a pickup exactly AT the supplied instant is refused,
-- one microsecond later passes. Security INVOKER (no SECURITY DEFINER),
-- schema-qualified at every call site.
CREATE OR REPLACE FUNCTION public.linkmia_pickup_is_future(p_pickup TIMESTAMPTZ, p_at TIMESTAMPTZ)
RETURNS BOOLEAN
LANGUAGE sql IMMUTABLE STRICT
AS $prt_helper$ SELECT p_pickup > p_at $prt_helper$;

DO $prt_helper_acl$
DECLARE
  v_owner OID;
  v_owner_name TEXT;
  v_allowed OID[];
  v_grantees OID[];
  v_grantee OID;
  v_row RECORD;
BEGIN
  SELECT proowner INTO v_owner FROM prt_pre_state WHERE proname = 'accept_quote_create';
  IF v_owner IS NULL THEN
    RAISE EXCEPTION 'PR-T: captured writer owner missing';
  END IF;
  SELECT rolname INTO v_owner_name FROM pg_roles WHERE oid = v_owner;
  EXECUTE format('ALTER FUNCTION public.linkmia_pickup_is_future(timestamptz,timestamptz) OWNER TO %I', v_owner_name);
  SELECT array_agg(DISTINCT proowner ORDER BY proowner) INTO v_allowed FROM prt_pre_state;
  EXECUTE 'REVOKE EXECUTE ON FUNCTION public.linkmia_pickup_is_future(timestamptz,timestamptz) FROM PUBLIC';
  FOR v_row IN SELECT rolname FROM pg_roles WHERE rolname IN ('anon','authenticated','service_role') LOOP
    EXECUTE format('REVOKE EXECUTE ON FUNCTION public.linkmia_pickup_is_future(timestamptz,timestamptz) FROM %I', v_row.rolname);
  END LOOP;
  FOR v_row IN SELECT DISTINCT r.rolname FROM prt_pre_state s JOIN pg_roles r ON r.oid = s.proowner
      WHERE s.proowner <> v_owner LOOP
    EXECUTE format('GRANT EXECUTE ON FUNCTION public.linkmia_pickup_is_future(timestamptz,timestamptz) TO %I', v_row.rolname);
  END LOOP;
  -- CANONICALIZE: revoke every EXECUTE grantee outside the allowed set
  -- (grantee 0 is PUBLIC). Materialized first, then revoked.
  SELECT array_agg(DISTINCT (x.a).grantee) INTO v_grantees
    FROM (SELECT aclexplode(p.proacl) AS a FROM pg_proc p
          WHERE p.oid = 'public.linkmia_pickup_is_future(timestamptz,timestamptz)'::regprocedure) x
    WHERE (x.a).privilege_type = 'EXECUTE'
      AND ((x.a).grantee = 0 OR NOT ((x.a).grantee = ANY (v_allowed)));
  FOREACH v_grantee IN ARRAY COALESCE(v_grantees, ARRAY[]::OID[]) LOOP
    IF v_grantee = 0 THEN
      EXECUTE 'REVOKE EXECUTE ON FUNCTION public.linkmia_pickup_is_future(timestamptz,timestamptz) FROM PUBLIC';
    ELSE
      EXECUTE format('REVOKE EXECUTE ON FUNCTION public.linkmia_pickup_is_future(timestamptz,timestamptz) FROM %I', pg_get_userbyid(v_grantee));
    END IF;
  END LOOP;
END;
$prt_helper_acl$;

CREATE OR REPLACE FUNCTION accept_quote_create(
  p_auth_user_id UUID,
  p_customer_id UUID,
  p_operation_request_id UUID,
  p_request_digest TEXT,
  p_verdict TEXT,               -- 'verified' | 'no_token' | 'verify_failed';
                                -- authentic stale/future tokens stay verified
  p_jti UUID,                   -- NULL unless verified (an UNVERIFIED jti
                                --   must never reach a keyed lookup)
  p_token_digest TEXT,          -- SHA-256 of the RAW PRESENTED token,
                                --   computed WITHOUT verification; NULL
                                --   only when no token was presented.
                                --   This is what makes Path A work after
                                --   expiry or key retirement.
  p_payload JSONB,              -- verified projection, NULL unless verified
  p_client_price NUMERIC,       -- the client-submitted price (off/observe)
  p_canonical_place_id TEXT,    -- the commitment-verified canonical id (NULL unless verified)
  p_airport_code TEXT,          -- trusted endpoint output after commitment verification
  p_vehicle_key TEXT,           -- canonical key; must equal payload.vehicle
  p_booking JSONB               -- booking column values from the endpoint
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions, pg_temp AS $$
DECLARE
  v_mode TEXT;
  v_high_water TIMESTAMPTZ;
  v_receipt operation_receipts%ROWTYPE;
  v_accept quote_acceptances%ROWTYPE;
  v_booking_id UUID;
  v_price NUMERIC;
  v_cents INTEGER;
  v_authority TEXT;
  v_idhash TEXT := encode(extensions.digest(p_auth_user_id::text, 'sha256'), 'hex');
  v_constraint TEXT;
  v_effective_verdict TEXT := p_verdict;
  v_has_request_id BOOLEAN;
  v_now_ms BIGINT;
  v_pickup_at TIMESTAMPTZ;
  v_passengers INTEGER;
  v_bags INTEGER;
  v_booking_mode TEXT;
  v_duration_minutes INTEGER;
  v_referred_by_host UUID;
  v_commission_rate NUMERIC := 0;
  v_host_commission NUMERIC := 0;
BEGIN
  IF p_auth_user_id IS NULL OR p_customer_id IS NULL THEN
    RAISE EXCEPTION 'authenticated identities are required';
  END IF;
  IF p_verdict IS NULL OR p_verdict NOT IN ('verified','no_token','verify_failed') THEN
    RAISE EXCEPTION 'unknown verdict %', COALESCE(p_verdict, 'NULL');
  END IF;
  IF (p_operation_request_id IS NULL) <> (p_request_digest IS NULL) THEN
    RAISE EXCEPTION 'operation_request_id and request_digest must be supplied together';
  END IF;
  v_has_request_id := p_operation_request_id IS NOT NULL;
  IF p_request_digest IS NOT NULL AND p_request_digest !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'request_digest must be lowercase SHA-256 hex';
  END IF;
  IF p_token_digest IS NOT NULL AND p_token_digest !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'token_digest must be lowercase SHA-256 hex';
  END IF;
  -- Validate once in every mode. Enforce does not use the browser price for
  -- money, but telemetry must never be able to turn NaN/Infinity/overflow
  -- into an unhandled INTEGER cast.
  IF p_client_price IS NOT NULL AND (
       p_client_price::text IN ('NaN','Infinity','-Infinity')
    OR p_client_price < 0 OR p_client_price > 21474836.47
  ) THEN
    RAISE EXCEPTION 'client price must be finite, non-negative, and representable as INTEGER cents';
  END IF;
  IF p_booking IS NULL OR jsonb_typeof(p_booking) IS DISTINCT FROM 'object' THEN
    RAISE EXCEPTION 'booking must be an object';
  END IF;
  v_pickup_at := (p_booking->>'pickup_datetime')::TIMESTAMPTZ;
  v_passengers := (p_booking->>'passengers')::INTEGER;
  v_bags := COALESCE((p_booking->>'bags')::INTEGER, 0);
  v_booking_mode := p_booking->>'booking_mode';
  v_duration_minutes := NULLIF(p_booking->>'duration_minutes','')::INTEGER;
  IF v_pickup_at IS NULL
     OR v_passengers IS NULL OR v_passengers < 1 OR v_passengers > 12
     OR v_bags < 0 OR v_bags > 15
     OR v_booking_mode IS NULL OR v_booking_mode NOT IN ('pickup','dropoff')
     OR (v_duration_minutes IS NOT NULL
       AND (v_duration_minutes < 1 OR v_duration_minutes > 1440))
     THEN
    RAISE EXCEPTION 'booking ride details are invalid';
  END IF;
  IF p_verdict = 'verified' AND (p_jti IS NULL OR p_token_digest IS NULL
      OR p_payload IS NULL OR p_canonical_place_id IS NULL
      OR p_airport_code IS NULL OR p_vehicle_key IS NULL) THEN
    RAISE EXCEPTION 'a verified consumption requires jti, digest, payload, canonical place, airport, and vehicle';
  ELSIF p_verdict = 'no_token' AND
     (p_token_digest IS NOT NULL OR p_jti IS NOT NULL OR p_payload IS NOT NULL
      OR p_canonical_place_id IS NOT NULL OR p_airport_code IS NOT NULL
      OR p_vehicle_key IS NOT NULL) THEN
    RAISE EXCEPTION 'no_token input may not carry token or canonical data';
  ELSIF p_verdict = 'verify_failed' AND
     (p_token_digest IS NULL OR p_jti IS NOT NULL OR p_payload IS NOT NULL
      OR p_canonical_place_id IS NOT NULL OR p_airport_code IS NOT NULL
      OR p_vehicle_key IS NOT NULL) THEN
    RAISE EXCEPTION 'verify_failed requires only the presented token digest';
  END IF;
  IF p_verdict = 'verified'
     AND jsonb_typeof(p_payload) IS DISTINCT FROM 'object' THEN
    RAISE EXCEPTION 'verified create payload projection is invalid';
  END IF;
  IF p_verdict = 'verified' AND (
       (SELECT count(*) FROM jsonb_object_keys(p_payload)) <> 16
    OR NOT (p_payload ?& ARRAY[
      'v','kid','jti','purpose','authUserId','customerId','vehicle',
      'pickupAtMs','commitment','routeQuality','finalCents','pricingVersion',
      'engineVersion','resolvedVersion','iat','exp'
    ])
    OR jsonb_typeof(p_payload->'v') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'kid') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'jti') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'purpose') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'authUserId') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'customerId') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'vehicle') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'pickupAtMs') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'commitment') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'routeQuality') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'finalCents') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'pricingVersion') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'engineVersion') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'resolvedVersion') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'iat') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'exp') IS DISTINCT FROM 'number'
  ) THEN
    RAISE EXCEPTION 'verified create payload projection is invalid';
  END IF;
  IF p_verdict = 'verified' AND (
       (p_payload->>'v')::NUMERIC IS DISTINCT FROM 2::NUMERIC
    OR (p_payload->>'pickupAtMs')::NUMERIC <> trunc((p_payload->>'pickupAtMs')::NUMERIC)
    OR (p_payload->>'pickupAtMs')::NUMERIC < 0
    OR (p_payload->>'pickupAtMs')::NUMERIC > 8640000000000000
    OR p_payload->>'kid' !~ '^[A-Za-z0-9._-]{1,64}$'
    OR p_payload->>'jti' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    OR p_payload->>'authUserId' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    OR p_payload->>'customerId' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    OR p_payload->>'authUserId' = '00000000-0000-0000-0000-000000000000'
    OR p_payload->>'customerId' = '00000000-0000-0000-0000-000000000000'
    OR p_payload->>'vehicle' !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'
    OR p_payload->>'commitment' !~ '^[0-9a-f]{64}$'
    OR p_payload->>'routeQuality' NOT IN ('traffic_aware','fallback')
    OR p_payload->>'pricingVersion' !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'
    OR p_payload->>'engineVersion' !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'
    OR p_payload->>'resolvedVersion' !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'
  ) THEN
    RAISE EXCEPTION 'verified create payload projection is invalid';
  END IF;
  IF p_verdict = 'verified' AND (
       p_payload->>'purpose' IS DISTINCT FROM 'create'
    OR (p_payload->>'jti')::UUID IS DISTINCT FROM p_jti
    OR (p_payload->>'authUserId')::UUID IS DISTINCT FROM p_auth_user_id
    OR (p_payload->>'customerId')::UUID IS DISTINCT FROM p_customer_id
  ) THEN
    RAISE EXCEPTION 'verified payload context does not match create caller';
  END IF;
  IF p_verdict = 'verified' AND (
       p_airport_code NOT IN ('MIA','FLL','PBI')
    OR p_vehicle_key NOT IN ('tesla','escalade','sprinter')
    OR p_payload->>'vehicle' IS DISTINCT FROM p_vehicle_key
  ) THEN
    RAISE EXCEPTION 'verified canonical airport/vehicle context is invalid';
  END IF;
  IF p_verdict = 'verified' AND (
       jsonb_typeof(p_payload->'iat') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'exp') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'finalCents') IS DISTINCT FROM 'number'
    OR (p_payload->>'iat')::NUMERIC <> trunc((p_payload->>'iat')::NUMERIC)
    OR (p_payload->>'exp')::NUMERIC <> trunc((p_payload->>'exp')::NUMERIC)
    OR (p_payload->>'iat')::NUMERIC < 0
    OR (p_payload->>'iat')::NUMERIC > 8640000000000000
    OR (p_payload->>'exp')::NUMERIC < 0
    OR (p_payload->>'exp')::NUMERIC > 8640000000000000
    OR (p_payload->>'exp')::NUMERIC - (p_payload->>'iat')::NUMERIC <> 900000
    OR (p_payload->>'finalCents')::NUMERIC <> trunc((p_payload->>'finalCents')::NUMERIC)
    OR (p_payload->>'finalCents')::NUMERIC < 0
    OR (p_payload->>'finalCents')::NUMERIC > 2147483647
  ) THEN
    RAISE EXCEPTION 'verified payload has invalid time or money semantics';
  END IF;
  -- pickupAtMs is part of the signed projection. Mode/passengers and the
  -- quantized route facts are commitment-verified by the Node endpoint and
  -- arrive here as validated typed booking fields; their provenance is
  -- recorded in quote_acceptances rather than inferred from client text.
  IF p_verdict = 'verified' AND
     v_pickup_at IS DISTINCT FROM
       to_timestamp(((p_payload->>'pickupAtMs')::BIGINT) / 1000.0) THEN
    RAISE EXCEPTION 'verified pickup time does not match booking';
  END IF;
  -- Mode, share-locked for the whole transaction (plan v5 C7/C8).
  SELECT ps.mode, ps.enforcement_started_at INTO v_mode, v_high_water
    FROM pricing_state ps WHERE ps.singleton FOR SHARE;
  IF v_mode IS NULL THEN
    RAISE EXCEPTION 'pricing_state singleton missing';
  END IF;
  -- Impossible-state fence (plan v5 C10): the valve makes these modes
  -- unreachable after the high-water mark; if we ever see one anyway,
  -- something bypassed the valve — refuse rather than write.
  IF v_high_water IS NOT NULL AND v_mode IN ('off','observe') THEN
    RAISE EXCEPTION 'impossible pricing state: mode % after enforcement began', v_mode;
  END IF;

  -- Universal idempotency FIRST — even before the blocked gate (plan
  -- v5 C11: "the operation-request receipt is checked first"). A retry
  -- of an ALREADY-COMPLETED booking arriving during a blocked emergency
  -- must report the passenger's real, existing ride — an idempotent
  -- readback creates nothing and consumes no jti, so C10 is preserved.
  IF v_has_request_id THEN
    -- Serialize retries of the same user action. The UNIQUE receipt remains
    -- the durable invariant; this transaction lock closes the miss-then-write
    -- window so the second transaction observes the first receipt.
    PERFORM pg_advisory_xact_lock(hashtextextended(p_operation_request_id::text, 17017));
    SELECT * INTO v_receipt FROM operation_receipts
      WHERE operation_request_id = p_operation_request_id;
    IF FOUND THEN
      IF v_receipt.auth_user_id = p_auth_user_id
         AND v_receipt.customer_id = p_customer_id
         AND v_receipt.kind = 'create'
         AND v_receipt.request_digest = p_request_digest THEN
        RETURN jsonb_build_object('outcome', 'idempotent', 'booking_id', v_receipt.booking_id);
      END IF;
      INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
        VALUES (CASE
                  WHEN v_receipt.auth_user_id IS DISTINCT FROM p_auth_user_id
                    OR v_receipt.customer_id IS DISTINCT FROM p_customer_id
                  THEN 'replay_identity_mismatch'
                  ELSE 'replay_context_mismatch'
                END, v_mode, 'create', v_idhash);
      RETURN jsonb_build_object('outcome', 'conflict');
    END IF;
  END IF;

  IF v_mode = 'blocked' THEN
    INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
      VALUES ('blocked', v_mode, 'create', v_idhash);
    RETURN jsonb_build_object('outcome', 'blocked');
  END IF;

  -- Legacy callers may omit an operation id only while pricing authority is
  -- still off/observe. Enforce refuses them before a quote can be consumed.
  IF NOT v_has_request_id AND v_mode IN ('enforce','blocked') THEN
    INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
      VALUES ('no_request_id', v_mode, 'create', v_idhash);
    RETURN jsonb_build_object('outcome', 'outdated_client');
  END IF;
  -- In off/observe the missing-operation-id evidence is written only after
  -- the booking exists, so its booking_id is truthful. Enforce still refuses
  -- above before any business write.

  -- Exact-digest token retry (plan v5 C11 Path A): even expired, even
  -- after key retirement — identity-gated.
  IF p_token_digest IS NOT NULL THEN
    SELECT * INTO v_accept FROM quote_acceptances WHERE token_digest = p_token_digest;
    IF FOUND THEN
      IF v_accept.auth_user_id = p_auth_user_id
         AND v_accept.customer_id = p_customer_id
         AND v_accept.purpose = 'create' THEN
        INSERT INTO quote_verifications (verdict, mode, purpose, jti, token_digest, booking_id, identity_hash)
          VALUES ('replay_idempotent', v_mode, 'create', v_accept.jti, p_token_digest, v_accept.booking_id, v_idhash);
        RETURN jsonb_build_object('outcome', 'idempotent', 'booking_id', v_accept.booking_id);
      END IF;
      INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
        VALUES (CASE
                  WHEN v_accept.auth_user_id IS DISTINCT FROM p_auth_user_id
                    OR v_accept.customer_id IS DISTINCT FROM p_customer_id
                  THEN 'replay_identity_mismatch'
                  ELSE 'replay_context_mismatch'
                END, v_mode, 'create', v_idhash);
      RETURN jsonb_build_object('outcome', 'refused');
    END IF;
  END IF;

  -- Sibling-token check (same quote, different vehicle token).
  IF p_jti IS NOT NULL THEN
    SELECT * INTO v_accept FROM quote_acceptances WHERE jti = p_jti;
    IF FOUND THEN
      IF v_accept.auth_user_id = p_auth_user_id
         AND v_accept.customer_id = p_customer_id
         AND v_accept.purpose = 'create' THEN
        INSERT INTO quote_verifications (verdict, mode, purpose, jti, booking_id, identity_hash)
          VALUES (CASE WHEN v_mode = 'enforce' THEN 'quote_consumed' ELSE 'would_quote_consumed' END,
                  v_mode, 'create', p_jti, v_accept.booking_id, v_idhash);
        RETURN jsonb_build_object('outcome', 'quote_consumed', 'booking_id', v_accept.booking_id);
      END IF;
      INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
        VALUES (CASE
                  WHEN v_accept.auth_user_id IS DISTINCT FROM p_auth_user_id
                    OR v_accept.customer_id IS DISTINCT FROM p_customer_id
                  THEN 'replay_identity_mismatch'
                  ELSE 'replay_context_mismatch'
                END, v_mode, 'create', v_idhash);
      RETURN jsonb_build_object('outcome', 'refused');
    END IF;
  END IF;

  -- Recheck time in the database immediately before any NEW consumption.
  -- Exact-digest and already-consumed-jti paths above remain recoverable after
  -- expiry/key retirement; a fresh acceptance never does.
  IF p_verdict = 'verified' THEN
    v_now_ms := floor(extract(epoch FROM clock_timestamp()) * 1000)::BIGINT;
    IF (p_payload->>'iat')::BIGINT > v_now_ms + 60000 THEN
      v_effective_verdict := 'not_yet_valid';
    ELSIF v_now_ms >= (p_payload->>'exp')::BIGINT THEN
      v_effective_verdict := 'expired';
    END IF;
  END IF;

  -- Enforcement requires authenticity. An authentic but stale/future token
  -- is refused in EVERY mode: observe/off may compare a currently valid quote,
  -- but may never turn an unconsumable quote into a new business write.
  IF v_mode = 'enforce' AND p_verdict <> 'verified' THEN
    INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
      VALUES (CASE WHEN p_verdict = 'no_token'
                THEN 'rejected_no_token' ELSE 'rejected_invalid' END,
              v_mode, 'create', v_idhash);
    RETURN jsonb_build_object('outcome',
      CASE WHEN p_verdict = 'no_token' THEN 'quote_required' ELSE 'quote_invalid' END);
  END IF;
  IF p_verdict = 'verified' AND v_effective_verdict <> 'verified' THEN
    INSERT INTO quote_verifications (
      verdict, mode, purpose, jti, token_digest, identity_hash
    ) VALUES (v_effective_verdict, v_mode, 'create', p_jti, p_token_digest, v_idhash);
    RETURN jsonb_build_object('outcome', CASE
      WHEN v_effective_verdict = 'expired' THEN 'quote_expired'
      ELSE 'quote_not_yet_valid' END);
  END IF;

  -- Authority (plan v5 C7 matrix).
  IF v_mode = 'enforce' THEN
    v_cents := (p_payload->>'finalCents')::INTEGER;
    v_price := v_cents / 100.0;
    v_authority := 'server_quote';
  ELSIF v_mode = 'observe' THEN
    IF p_client_price IS NULL THEN
      RAISE EXCEPTION 'off/observe modes require a safe client price';
    END IF;
    v_price := round(p_client_price * 100) / 100.0;
    v_cents := round(p_client_price * 100)::INTEGER;
    v_authority := 'client_observe';
  ELSE
    IF p_client_price IS NULL THEN
      RAISE EXCEPTION 'off/observe modes require a safe client price';
    END IF;
    v_price := round(p_client_price * 100) / 100.0;
    v_cents := round(p_client_price * 100)::INTEGER;
    v_authority := 'client_legacy';
  END IF;

  v_referred_by_host := NULLIF(p_booking->>'referred_by_host','')::UUID;
  IF v_referred_by_host IS NOT NULL THEN
    SELECT h.commission_rate INTO v_commission_rate
      FROM hosts h
      WHERE h.id = v_referred_by_host AND h.status = 'active'
      FOR SHARE;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'referred host is not active';
    END IF;
    IF v_commission_rate IS NULL OR v_commission_rate < 0 OR v_commission_rate > 1 THEN
      RAISE EXCEPTION 'referred host commission rate is invalid';
    END IF;
  END IF;
  v_host_commission := round(v_price * COALESCE(v_commission_rate, 0), 2);

  -- PR-T pre-mutation pickup guard: transaction-stable clock, OUTSIDE every
  -- verified-only branch (all three verdicts obey it). An elapsed pickup
  -- returns before any business write; the guard itself records nothing.
  -- Pre-existing and deliberately NOT moved: the edit writer's inherited
  -- 017 telemetry row for an operationId-less caller in off/observe
  -- ('no_request_id', written ABOVE this guard, outside the subtransaction)
  -- is the one row such a legacy caller still leaves — pinned by the
  -- executed suite. The browser always sends an operationId.
  IF NOT public.linkmia_pickup_is_future(v_pickup_at, transaction_timestamp()) THEN
    RETURN jsonb_build_object('outcome', 'pickup_time_elapsed');
  END IF;

  PERFORM set_config('linkmia.rpc_writer', 'on', TRUE);
  BEGIN
    INSERT INTO bookings (
      trip_id, customer_id, customer_name, customer_phone, customer_email,
      booker_name, booker_phone,
      pickup_location, dropoff_location, pickup_datetime,
      passengers, bags, vehicle_type, vehicle_name,
      price, price_cents, price_authority,
      canonical_place_id, airport_code, route_authority,
      booking_mode, payment_status, payment_method,
      flight_number, notes, pickup_sign, promo_code,
      referred_by_host, host_commission, duration_minutes,
      status, source
    ) VALUES (
      p_booking->>'trip_id', p_customer_id,
      p_booking->>'customer_name', p_booking->>'customer_phone', p_booking->>'customer_email',
      p_booking->>'booker_name', p_booking->>'booker_phone',
      p_booking->>'pickup_location', p_booking->>'dropoff_location',
      v_pickup_at,
      v_passengers,
      v_bags,
      CASE WHEN p_verdict = 'verified' THEN CASE p_vehicle_key
        WHEN 'tesla' THEN 'sedan' WHEN 'escalade' THEN 'suv'
        WHEN 'sprinter' THEN 'sprinter' END
        ELSE p_booking->>'vehicle_type' END,
      CASE WHEN p_verdict = 'verified' THEN CASE p_vehicle_key
        WHEN 'tesla' THEN 'Tesla Model Y'
        WHEN 'escalade' THEN 'Cadillac Escalade'
        WHEN 'sprinter' THEN 'Mercedes Sprinter' END
        ELSE p_booking->>'vehicle_name' END,
      v_price, v_cents, v_authority,
      CASE WHEN v_effective_verdict = 'verified' AND v_mode <> 'off'
        THEN p_canonical_place_id ELSE NULL END,
      CASE WHEN v_effective_verdict = 'verified' AND v_mode <> 'off'
        THEN p_airport_code ELSE NULL END,
      CASE WHEN v_effective_verdict = 'verified' AND v_mode <> 'off'
        THEN 'canonical' ELSE 'legacy_text' END,
      v_booking_mode, COALESCE(p_booking->>'payment_status','unpaid'),
      COALESCE(p_booking->>'payment_method','cash'),
      p_booking->>'flight_number', p_booking->>'notes',
      p_booking->>'pickup_sign', p_booking->>'promo_code',
      v_referred_by_host,
      v_host_commission,
      -- R1 (address plan v3, ordered prerequisite): provider route duration
      -- is Google Maps Content with no retention exception (case 74801827),
      -- so it is never persisted in any pricing mode. The submitted value is
      -- still bounds-checked above for input strictness, then discarded.
      -- Displays already degrade on NULL (trip ETA block, doorbell eta line).
      NULL::INTEGER,
      'pending', COALESCE(p_booking->>'source','website')
    ) RETURNING id INTO v_booking_id;

    IF v_effective_verdict = 'verified' THEN
      INSERT INTO quote_acceptances (
        jti, token_digest, booking_id, purpose, auth_user_id, customer_id,
        kid, vehicle_key, final_cents, client_cents, authority,
        pricing_version, engine_version, resolved_version,
        canonical_place_id, airport_code, booking_mode, pickup_at, passengers,
        payload_projection
      ) VALUES (
        p_jti, p_token_digest, v_booking_id, 'create', p_auth_user_id, p_customer_id,
        p_payload->>'kid', p_vehicle_key, (p_payload->>'finalCents')::INTEGER,
        CASE WHEN v_mode <> 'enforce' THEN v_cents ELSE NULL END,
        v_authority,
        p_payload->>'pricingVersion', p_payload->>'engineVersion', p_payload->>'resolvedVersion',
        p_canonical_place_id, p_airport_code,
        v_booking_mode,
        to_timestamp(((p_payload->>'pickupAtMs')::BIGINT) / 1000.0),
        v_passengers,
        -- R1 fail-closed acceptance projection: an explicit ALLOWLIST of the
        -- token's non-provider fields. routeQuality (Google Routes
        -- fallbackInfo) is excluded, and any future token field stays out
        -- until it is named here. Distance/duration exist only inside the
        -- keyed commitment hash and were never plaintext.
        jsonb_build_object(
          'v', p_payload->'v',
          'kid', p_payload->'kid',
          'jti', p_payload->'jti',
          'purpose', p_payload->'purpose',
          'authUserId', p_payload->'authUserId',
          'customerId', p_payload->'customerId',
          'vehicle', p_payload->'vehicle',
          'pickupAtMs', p_payload->'pickupAtMs',
          'commitment', p_payload->'commitment',
          'finalCents', p_payload->'finalCents',
          'pricingVersion', p_payload->'pricingVersion',
          'engineVersion', p_payload->'engineVersion',
          'resolvedVersion', p_payload->'resolvedVersion',
          'iat', p_payload->'iat',
          'exp', p_payload->'exp'
        )
      );
    END IF;

    IF v_has_request_id THEN
      INSERT INTO operation_receipts (
        operation_request_id, kind, auth_user_id, customer_id,
        request_digest, booking_id
      ) VALUES (
        p_operation_request_id, 'create', p_auth_user_id, p_customer_id,
        p_request_digest, v_booking_id
      );
    END IF;

    IF NOT v_has_request_id THEN
      INSERT INTO quote_verifications (
        verdict, mode, purpose, booking_id, identity_hash
      ) VALUES ('no_request_id', v_mode, 'create', v_booking_id, v_idhash);
    END IF;

    -- The booking/acceptance/receipt inserts above can wait on unique-index
    -- conflicts. If the competing transaction rolls back after this token's
    -- expiry, our inserts can then succeed. Recheck at the final write
    -- boundary and raise inside this subtransaction: the dedicated handler
    -- below records the refusal only after every business write rolls back.
    IF p_verdict = 'verified' THEN
      v_now_ms := floor(extract(epoch FROM clock_timestamp()) * 1000)::BIGINT;
      IF (p_payload->>'iat')::BIGINT > v_now_ms + 60000 THEN
        v_effective_verdict := 'not_yet_valid';
      ELSIF v_now_ms >= (p_payload->>'exp')::BIGINT THEN
        v_effective_verdict := 'expired';
      END IF;
      IF v_effective_verdict <> 'verified' THEN
        RAISE EXCEPTION USING ERRCODE = 'ZQ017', MESSAGE = v_effective_verdict;
      END IF;
    END IF;

    -- Stored jti/digest are VERIFIED-ONLY (the table's contract): an
    -- unverifiable token's digest is used for the Path-A lookup above
    -- but never persisted as evidence.
    INSERT INTO quote_verifications (
      verdict, mode, purpose, jti, token_digest, booking_id, identity_hash,
      client_cents, server_cents
    ) VALUES (
      v_effective_verdict,
      v_mode, 'create',
      CASE WHEN v_effective_verdict = 'verified' THEN p_jti ELSE NULL END,
      CASE WHEN v_effective_verdict = 'verified' THEN p_token_digest ELSE NULL END,
      v_booking_id, v_idhash,
      CASE WHEN p_client_price IS NOT NULL THEN round(p_client_price * 100)::INTEGER ELSE NULL END,
      CASE WHEN p_verdict = 'verified' THEN (p_payload->>'finalCents')::INTEGER ELSE NULL END
    );

    -- PR-T final pickup guard: the LAST potentially blocking statement in
    -- this subtransaction — AFTER the telemetry insert, on the live clock.
    -- A pickup that elapsed during any lock wait rolls every write back.
    IF NOT public.linkmia_pickup_is_future(v_pickup_at, clock_timestamp()) THEN
      RAISE EXCEPTION USING ERRCODE = 'ZQ019', MESSAGE = 'pickup_time_elapsed';
    END IF;
    PERFORM set_config('linkmia.rpc_writer', 'off', TRUE);
    RETURN jsonb_build_object('outcome', 'created', 'booking_id', v_booking_id,
                              'authority', v_authority);

  EXCEPTION WHEN SQLSTATE 'ZQ017' THEN
    PERFORM set_config('linkmia.rpc_writer', 'off', TRUE);
    INSERT INTO quote_verifications (
      verdict, mode, purpose, jti, token_digest, identity_hash
    ) VALUES (v_effective_verdict, v_mode, 'create', p_jti, p_token_digest, v_idhash);
    RETURN jsonb_build_object('outcome', CASE
      WHEN v_effective_verdict = 'expired' THEN 'quote_expired'
      ELSE 'quote_not_yet_valid' END);

  WHEN SQLSTATE 'ZQ019' THEN
    -- PR-T: every booking/acceptance/receipt/telemetry write INSIDE the
    -- subtransaction rolled back with it. No verdict row is written by the
    -- guard (the closed verdict CHECK is untouched) and v_effective_verdict
    -- is never changed. A telemetry row written BEFORE the block (the edit
    -- writer's operationId-less 'no_request_id' instrument) is outside it
    -- and survives, exactly as it did before PR-T.
    PERFORM set_config('linkmia.rpc_writer', 'off', TRUE);
    RETURN jsonb_build_object('outcome', 'pickup_time_elapsed');

  WHEN unique_violation THEN
    PERFORM set_config('linkmia.rpc_writer', 'off', TRUE);
    GET STACKED DIAGNOSTICS v_constraint = CONSTRAINT_NAME;
    -- Constraint-name branching is mandatory (plan v2 §3): with several
    -- unique constraints live, a bare handler would misread one race
    -- as another. NOTE: everything inside the block above — including
    -- its telemetry rows — rolled back with the subtransaction, so the
    -- LOSING attempt's evidence is written HERE, where it commits.
    IF v_constraint = 'bookings_one_active_per_customer' THEN
      -- A same-operation retry can lose on the active-slot index before its
      -- receipt insert is observed. Re-read and classify it before reporting
      -- a different active booking.
      IF v_has_request_id THEN
        SELECT * INTO v_receipt FROM operation_receipts
          WHERE operation_request_id = p_operation_request_id;
        IF FOUND THEN
          IF v_receipt.auth_user_id = p_auth_user_id
             AND v_receipt.customer_id = p_customer_id
             AND v_receipt.kind = 'create'
             AND v_receipt.request_digest = p_request_digest THEN
            RETURN jsonb_build_object('outcome', 'idempotent',
              'booking_id', v_receipt.booking_id);
          END IF;
          INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
            VALUES (CASE
                      WHEN v_receipt.auth_user_id IS DISTINCT FROM p_auth_user_id
                        OR v_receipt.customer_id IS DISTINCT FROM p_customer_id
                      THEN 'replay_identity_mismatch'
                      ELSE 'replay_context_mismatch'
                    END, v_mode, 'create', v_idhash);
          RETURN jsonb_build_object('outcome', 'conflict');
        END IF;
      END IF;
      SELECT id INTO v_booking_id FROM bookings
        WHERE active_slot = p_customer_id;
      INSERT INTO quote_verifications (verdict, mode, purpose, jti, booking_id, identity_hash)
        VALUES ('active_conflict', v_mode, 'create', p_jti, v_booking_id, v_idhash);
      RETURN jsonb_build_object('outcome', 'active_exists', 'booking_id', v_booking_id);
    ELSIF v_constraint IN ('quote_acceptances_jti_key', 'quote_acceptances_token_digest_key') THEN
      -- Lost the consumption race: re-classify under the identity gate.
      SELECT * INTO v_accept FROM quote_acceptances
        WHERE jti = p_jti OR token_digest = p_token_digest
        ORDER BY (token_digest = p_token_digest) DESC LIMIT 1;
      IF FOUND AND v_accept.auth_user_id = p_auth_user_id
               AND v_accept.customer_id = p_customer_id
               AND v_accept.purpose = 'create' THEN
        IF v_accept.token_digest = p_token_digest THEN
          INSERT INTO quote_verifications (verdict, mode, purpose, jti, token_digest, booking_id, identity_hash)
            VALUES ('replay_idempotent', v_mode, 'create', p_jti, p_token_digest, v_accept.booking_id, v_idhash);
          RETURN jsonb_build_object('outcome', 'idempotent', 'booking_id', v_accept.booking_id);
        END IF;
        INSERT INTO quote_verifications (verdict, mode, purpose, jti, booking_id, identity_hash)
          VALUES ('quote_consumed', v_mode, 'create', p_jti, v_accept.booking_id, v_idhash);
        RETURN jsonb_build_object('outcome', 'quote_consumed', 'booking_id', v_accept.booking_id);
      END IF;
      INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
        VALUES (CASE
                  WHEN FOUND AND v_accept.auth_user_id = p_auth_user_id
                    AND v_accept.customer_id = p_customer_id
                  THEN 'replay_context_mismatch'
                  ELSE 'replay_identity_mismatch'
                END, v_mode, 'create', v_idhash);
      RETURN jsonb_build_object('outcome', 'refused');
    ELSIF v_constraint = 'operation_receipts_operation_request_id_key' THEN
      SELECT * INTO v_receipt FROM operation_receipts
        WHERE operation_request_id = p_operation_request_id;
      IF FOUND AND v_receipt.auth_user_id = p_auth_user_id
               AND v_receipt.customer_id = p_customer_id
               AND v_receipt.kind = 'create'
               AND v_receipt.request_digest = p_request_digest THEN
        RETURN jsonb_build_object('outcome', 'idempotent', 'booking_id', v_receipt.booking_id);
      END IF;
      INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
        VALUES (CASE
                  WHEN FOUND AND (v_receipt.auth_user_id IS DISTINCT FROM p_auth_user_id
                    OR v_receipt.customer_id IS DISTINCT FROM p_customer_id)
                  THEN 'replay_identity_mismatch'
                  ELSE 'replay_context_mismatch'
                END, v_mode, 'create', v_idhash);
      RETURN jsonb_build_object('outcome', 'conflict');
    END IF;
    RAISE;
  END;
END $$;

CREATE OR REPLACE FUNCTION accept_quote_edit(
  p_auth_user_id UUID,
  p_customer_id UUID,
  p_operation_request_id UUID,
  p_request_digest TEXT,
  p_booking_id UUID,
  p_expected_details_version INTEGER,
  p_verdict TEXT,               -- authentic stale/future tokens stay verified
  p_jti UUID,
  p_token_digest TEXT,
  p_payload JSONB,
  p_client_price NUMERIC,
  p_canonical_place_id TEXT,    -- the commitment-verified canonical id (NULL unless verified)
  p_airport_code TEXT,          -- trusted endpoint output after commitment verification
  p_vehicle_key TEXT,           -- canonical key; must equal payload.vehicle
  p_edit JSONB                  -- the ride-detail column values
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions, pg_temp AS $$
DECLARE
  v_mode TEXT;
  v_high_water TIMESTAMPTZ;
  v_row bookings%ROWTYPE;
  v_receipt operation_receipts%ROWTYPE;
  v_accept quote_acceptances%ROWTYPE;
  v_price NUMERIC;
  v_cents INTEGER;
  v_authority TEXT;
  v_idhash TEXT := encode(extensions.digest(p_auth_user_id::text, 'sha256'), 'hex');
  v_constraint TEXT;
  v_effective_verdict TEXT := p_verdict;
  v_has_request_id BOOLEAN;
  v_now_ms BIGINT;
  v_row_found BOOLEAN;
  v_current_details_version INTEGER;
  v_pickup_at TIMESTAMPTZ;
  v_passengers INTEGER;
  v_bags INTEGER;
  v_booking_mode TEXT;
  v_duration_minutes INTEGER;
  v_customer_name TEXT;
  v_customer_phone TEXT;
  v_customer_email TEXT;
  v_booker_name TEXT;
  v_booker_phone TEXT;
  v_payment_method TEXT;
  v_commission_rate NUMERIC := 0;
  v_host_commission NUMERIC := 0;
BEGIN
  IF p_auth_user_id IS NULL OR p_customer_id IS NULL OR p_booking_id IS NULL THEN
    RAISE EXCEPTION 'authenticated identities and booking_id are required';
  END IF;
  IF p_verdict IS NULL OR p_verdict NOT IN ('verified','no_token','verify_failed') THEN
    RAISE EXCEPTION 'unknown verdict %', COALESCE(p_verdict, 'NULL');
  END IF;
  IF (p_operation_request_id IS NULL) <> (p_request_digest IS NULL) THEN
    RAISE EXCEPTION 'operation_request_id and request_digest must be supplied together';
  END IF;
  v_has_request_id := p_operation_request_id IS NOT NULL;
  IF p_request_digest IS NOT NULL AND p_request_digest !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'request_digest must be lowercase SHA-256 hex';
  END IF;
  IF p_token_digest IS NOT NULL AND p_token_digest !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'token_digest must be lowercase SHA-256 hex';
  END IF;
  IF p_client_price IS NOT NULL AND (
       p_client_price::text IN ('NaN','Infinity','-Infinity')
    OR p_client_price < 0 OR p_client_price > 21474836.47
  ) THEN
    RAISE EXCEPTION 'client price must be finite, non-negative, and representable as INTEGER cents';
  END IF;
  IF p_edit IS NOT NULL AND jsonb_typeof(p_edit) IS DISTINCT FROM 'object' THEN
    RAISE EXCEPTION 'edit must be an object';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM jsonb_object_keys(COALESCE(p_edit, '{}'::JSONB)) AS supplied(key)
    WHERE supplied.key <> ALL (ARRAY[
      'pickup_location','dropoff_location','pickup_datetime',
      'passengers','bags','vehicle_type','vehicle_name','booking_mode',
      'duration_minutes','customer_name','customer_phone','customer_email',
      'booker_name','booker_phone','payment_method','flight_number','notes',
      'pickup_sign','promo_code'
    ]::TEXT[])
  ) THEN
    RAISE EXCEPTION 'edit contains a protected or unknown field';
  END IF;
  IF p_verdict = 'verified' AND (p_jti IS NULL OR p_token_digest IS NULL
      OR p_payload IS NULL OR p_canonical_place_id IS NULL
      OR p_airport_code IS NULL OR p_vehicle_key IS NULL) THEN
    RAISE EXCEPTION 'a verified consumption requires jti, digest, payload, canonical place, airport, and vehicle';
  ELSIF p_verdict = 'no_token' AND
     (p_token_digest IS NOT NULL OR p_jti IS NOT NULL OR p_payload IS NOT NULL
      OR p_canonical_place_id IS NOT NULL OR p_airport_code IS NOT NULL
      OR p_vehicle_key IS NOT NULL) THEN
    RAISE EXCEPTION 'no_token input may not carry token or canonical data';
  ELSIF p_verdict = 'verify_failed' AND
     (p_token_digest IS NULL OR p_jti IS NOT NULL OR p_payload IS NOT NULL
      OR p_canonical_place_id IS NOT NULL OR p_airport_code IS NOT NULL
      OR p_vehicle_key IS NOT NULL) THEN
    RAISE EXCEPTION 'verify_failed requires only the presented token digest';
  END IF;
  IF p_verdict = 'verified'
     AND jsonb_typeof(p_payload) IS DISTINCT FROM 'object' THEN
    RAISE EXCEPTION 'verified edit payload projection is invalid';
  END IF;
  IF p_verdict = 'verified' AND (
       (SELECT count(*) FROM jsonb_object_keys(p_payload)) <> 18
    OR NOT (p_payload ?& ARRAY[
      'v','kid','jti','purpose','authUserId','customerId','bookingId',
      'assignmentEpoch','vehicle','pickupAtMs','commitment','routeQuality',
      'finalCents','pricingVersion','engineVersion','resolvedVersion','iat','exp'
    ])
    OR jsonb_typeof(p_payload->'v') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'kid') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'jti') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'purpose') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'authUserId') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'customerId') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'bookingId') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'assignmentEpoch') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'vehicle') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'pickupAtMs') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'commitment') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'routeQuality') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'finalCents') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'pricingVersion') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'engineVersion') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'resolvedVersion') IS DISTINCT FROM 'string'
    OR jsonb_typeof(p_payload->'iat') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'exp') IS DISTINCT FROM 'number'
  ) THEN
    RAISE EXCEPTION 'verified edit payload projection is invalid';
  END IF;
  IF p_verdict = 'verified' AND (
       (p_payload->>'v')::NUMERIC IS DISTINCT FROM 2::NUMERIC
    OR (p_payload->>'assignmentEpoch')::NUMERIC < 0
    OR (p_payload->>'assignmentEpoch')::NUMERIC > 2147483647
    OR (p_payload->>'assignmentEpoch')::NUMERIC <>
       trunc((p_payload->>'assignmentEpoch')::NUMERIC)
    OR (p_payload->>'pickupAtMs')::NUMERIC <> trunc((p_payload->>'pickupAtMs')::NUMERIC)
    OR (p_payload->>'pickupAtMs')::NUMERIC < 0
    OR (p_payload->>'pickupAtMs')::NUMERIC > 8640000000000000
    OR p_payload->>'kid' !~ '^[A-Za-z0-9._-]{1,64}$'
    OR p_payload->>'jti' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    OR p_payload->>'authUserId' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    OR p_payload->>'customerId' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    OR p_payload->>'bookingId' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    OR p_payload->>'authUserId' = '00000000-0000-0000-0000-000000000000'
    OR p_payload->>'customerId' = '00000000-0000-0000-0000-000000000000'
    OR p_payload->>'bookingId' = '00000000-0000-0000-0000-000000000000'
    OR p_payload->>'vehicle' !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'
    OR p_payload->>'commitment' !~ '^[0-9a-f]{64}$'
    OR p_payload->>'routeQuality' NOT IN ('traffic_aware','fallback')
    OR p_payload->>'pricingVersion' !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'
    OR p_payload->>'engineVersion' !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'
    OR p_payload->>'resolvedVersion' !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'
  ) THEN
    RAISE EXCEPTION 'verified edit payload projection is invalid';
  END IF;
  IF p_verdict = 'verified' AND (
       p_payload->>'purpose' IS DISTINCT FROM 'edit'
    OR (p_payload->>'jti')::UUID IS DISTINCT FROM p_jti
    OR (p_payload->>'authUserId')::UUID IS DISTINCT FROM p_auth_user_id
    OR (p_payload->>'customerId')::UUID IS DISTINCT FROM p_customer_id
  ) THEN
    RAISE EXCEPTION 'verified payload context does not match edit caller';
  END IF;
  IF p_verdict = 'verified' AND (
       p_airport_code NOT IN ('MIA','FLL','PBI')
    OR p_vehicle_key NOT IN ('tesla','escalade','sprinter')
    OR p_payload->>'vehicle' IS DISTINCT FROM p_vehicle_key
  ) THEN
    RAISE EXCEPTION 'verified canonical airport/vehicle context is invalid';
  END IF;
  IF p_verdict = 'verified' AND (
       jsonb_typeof(p_payload->'iat') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'exp') IS DISTINCT FROM 'number'
    OR jsonb_typeof(p_payload->'finalCents') IS DISTINCT FROM 'number'
    OR (p_payload->>'iat')::NUMERIC <> trunc((p_payload->>'iat')::NUMERIC)
    OR (p_payload->>'exp')::NUMERIC <> trunc((p_payload->>'exp')::NUMERIC)
    OR (p_payload->>'iat')::NUMERIC < 0
    OR (p_payload->>'iat')::NUMERIC > 8640000000000000
    OR (p_payload->>'exp')::NUMERIC < 0
    OR (p_payload->>'exp')::NUMERIC > 8640000000000000
    OR (p_payload->>'exp')::NUMERIC - (p_payload->>'iat')::NUMERIC <> 900000
    OR (p_payload->>'finalCents')::NUMERIC <> trunc((p_payload->>'finalCents')::NUMERIC)
    OR (p_payload->>'finalCents')::NUMERIC < 0
    OR (p_payload->>'finalCents')::NUMERIC > 2147483647
  ) THEN
    RAISE EXCEPTION 'verified payload has invalid time or money semantics';
  END IF;

  SELECT ps.mode, ps.enforcement_started_at INTO v_mode, v_high_water
    FROM pricing_state ps WHERE ps.singleton FOR SHARE;
  IF v_mode IS NULL THEN
    RAISE EXCEPTION 'pricing_state singleton missing';
  END IF;
  -- Impossible-state fence (plan v5 C10): the valve makes these modes
  -- unreachable after the high-water mark; if we ever see one anyway,
  -- something bypassed the valve — refuse rather than write.
  IF v_high_water IS NOT NULL AND v_mode IN ('off','observe') THEN
    RAISE EXCEPTION 'impossible pricing state: mode % after enforcement began', v_mode;
  END IF;
  -- Universal idempotency FIRST — even before the blocked gate (see
  -- the create RPC's note; same rule, same reason).
  IF v_has_request_id THEN
    PERFORM pg_advisory_xact_lock(hashtextextended(p_operation_request_id::text, 17017));
    SELECT * INTO v_receipt FROM operation_receipts
      WHERE operation_request_id = p_operation_request_id;
    IF FOUND THEN
      IF v_receipt.auth_user_id = p_auth_user_id
         AND v_receipt.customer_id = p_customer_id
         AND v_receipt.kind = 'edit_quoted'
         AND v_receipt.booking_id = p_booking_id
         AND v_receipt.request_digest = p_request_digest THEN
        SELECT details_version INTO v_current_details_version
          FROM bookings WHERE id = v_receipt.booking_id;
        RETURN jsonb_build_object('outcome', 'idempotent',
          'booking_id', v_receipt.booking_id, 'details_version', v_current_details_version);
      END IF;
      INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
        VALUES (CASE
                  WHEN v_receipt.auth_user_id IS DISTINCT FROM p_auth_user_id
                    OR v_receipt.customer_id IS DISTINCT FROM p_customer_id
                  THEN 'replay_identity_mismatch'
                  ELSE 'replay_context_mismatch'
                END, v_mode, 'edit', v_idhash);
      RETURN jsonb_build_object('outcome', 'conflict');
    END IF;
  END IF;

  IF v_mode = 'blocked' THEN
    INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
      VALUES ('blocked', v_mode, 'edit', v_idhash);
    RETURN jsonb_build_object('outcome', 'blocked');
  END IF;

  IF NOT v_has_request_id AND v_mode IN ('enforce','blocked') THEN
    INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
      VALUES ('no_request_id', v_mode, 'edit', v_idhash);
    RETURN jsonb_build_object('outcome', 'outdated_client');
  END IF;
  IF NOT v_has_request_id THEN
    INSERT INTO quote_verifications (verdict, mode, purpose, booking_id, identity_hash)
      VALUES ('no_request_id', v_mode, 'edit', p_booking_id, v_idhash);
  END IF;

  -- Exact-digest retry (identity-gated), then sibling check.
  IF p_token_digest IS NOT NULL THEN
    SELECT * INTO v_accept FROM quote_acceptances WHERE token_digest = p_token_digest;
    IF FOUND THEN
      -- An exact-digest hit is an idempotent EDIT retry only when it
      -- was an edit acceptance FOR THIS BOOKING by THIS identity. A
      -- same-identity CREATE-token digest replayed here must not
      -- report a phantom edit success.
      IF v_accept.auth_user_id = p_auth_user_id AND v_accept.customer_id = p_customer_id
         AND v_accept.purpose = 'edit' AND v_accept.booking_id = p_booking_id THEN
        SELECT details_version INTO v_current_details_version
          FROM bookings WHERE id = v_accept.booking_id;
        INSERT INTO quote_verifications (verdict, mode, purpose, jti, token_digest, booking_id, identity_hash)
          VALUES ('replay_idempotent', v_mode, 'edit', v_accept.jti, p_token_digest, v_accept.booking_id, v_idhash);
        RETURN jsonb_build_object('outcome', 'idempotent',
          'booking_id', v_accept.booking_id,
          'details_version', v_current_details_version);
      END IF;
      INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
        VALUES (CASE
                  WHEN v_accept.auth_user_id IS DISTINCT FROM p_auth_user_id
                    OR v_accept.customer_id IS DISTINCT FROM p_customer_id
                  THEN 'replay_identity_mismatch'
                  ELSE 'replay_context_mismatch'
                END, v_mode, 'edit', v_idhash);
      RETURN jsonb_build_object('outcome', 'refused');
    END IF;
  END IF;
  IF p_jti IS NOT NULL THEN
    SELECT * INTO v_accept FROM quote_acceptances WHERE jti = p_jti;
    IF FOUND THEN
      IF v_accept.auth_user_id = p_auth_user_id
         AND v_accept.customer_id = p_customer_id
         AND v_accept.purpose = 'edit'
         AND v_accept.booking_id = p_booking_id THEN
        INSERT INTO quote_verifications (verdict, mode, purpose, jti, booking_id, identity_hash)
          VALUES (CASE WHEN v_mode = 'enforce' THEN 'quote_consumed' ELSE 'would_quote_consumed' END,
                  v_mode, 'edit', p_jti, v_accept.booking_id, v_idhash);
        RETURN jsonb_build_object('outcome', 'quote_consumed', 'booking_id', v_accept.booking_id);
      END IF;
      INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
        VALUES (CASE
                  WHEN v_accept.auth_user_id IS DISTINCT FROM p_auth_user_id
                    OR v_accept.customer_id IS DISTINCT FROM p_customer_id
                  THEN 'replay_identity_mismatch'
                  ELSE 'replay_context_mismatch'
                END, v_mode, 'edit', v_idhash);
      RETURN jsonb_build_object('outcome', 'refused');
    END IF;
  END IF;

  -- Recheck time immediately before any new acceptance. Retry/consumed paths
  -- above intentionally precede this verdict.
  IF p_verdict = 'verified' THEN
    v_now_ms := floor(extract(epoch FROM clock_timestamp()) * 1000)::BIGINT;
    IF (p_payload->>'iat')::BIGINT > v_now_ms + 60000 THEN
      v_effective_verdict := 'not_yet_valid';
    ELSIF v_now_ms >= (p_payload->>'exp')::BIGINT THEN
      v_effective_verdict := 'expired';
    END IF;
  END IF;

  IF v_mode = 'enforce' AND p_verdict <> 'verified' THEN
    INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
      VALUES (CASE WHEN p_verdict = 'no_token'
                THEN 'rejected_no_token' ELSE 'rejected_invalid' END,
              v_mode, 'edit', v_idhash);
    RETURN jsonb_build_object('outcome',
      CASE WHEN p_verdict = 'no_token' THEN 'quote_required' ELSE 'quote_invalid' END);
  END IF;
  IF p_verdict = 'verified' AND v_effective_verdict <> 'verified' THEN
    INSERT INTO quote_verifications (
      verdict, mode, purpose, jti, token_digest, booking_id, identity_hash
    ) VALUES (v_effective_verdict, v_mode, 'edit', p_jti, p_token_digest,
              p_booking_id, v_idhash);
    RETURN jsonb_build_object('outcome', CASE
      WHEN v_effective_verdict = 'expired' THEN 'quote_expired'
      ELSE 'quote_not_yet_valid' END);
  END IF;

  -- The guarded row read: ownership, status, CAS, and ERA all checked
  -- against live truth under lock.
  SELECT * INTO v_row FROM bookings WHERE id = p_booking_id FOR UPDATE;
  v_row_found := FOUND;

  -- The row lock can outlive the token. Repeat the database-clock verdict
  -- after the wait and before any CAS or business write.
  IF p_verdict = 'verified' THEN
    v_now_ms := floor(extract(epoch FROM clock_timestamp()) * 1000)::BIGINT;
    IF (p_payload->>'iat')::BIGINT > v_now_ms + 60000 THEN
      INSERT INTO quote_verifications (
        verdict, mode, purpose, jti, token_digest, booking_id, identity_hash
      ) VALUES ('not_yet_valid', v_mode, 'edit', p_jti, p_token_digest,
                p_booking_id, v_idhash);
      RETURN jsonb_build_object('outcome', 'quote_not_yet_valid');
    ELSIF v_now_ms >= (p_payload->>'exp')::BIGINT THEN
      INSERT INTO quote_verifications (
        verdict, mode, purpose, jti, token_digest, booking_id, identity_hash
      ) VALUES ('expired', v_mode, 'edit', p_jti, p_token_digest,
                p_booking_id, v_idhash);
      RETURN jsonb_build_object('outcome', 'quote_expired');
    END IF;
  END IF;

  -- A concurrent retry may have waited on this row while the first request
  -- committed its receipt and version bump. Re-read before status/CAS exits.
  IF v_has_request_id THEN
    SELECT * INTO v_receipt FROM operation_receipts
      WHERE operation_request_id = p_operation_request_id;
    IF FOUND THEN
      IF v_receipt.auth_user_id = p_auth_user_id
         AND v_receipt.customer_id = p_customer_id
         AND v_receipt.kind = 'edit_quoted'
         AND v_receipt.booking_id = p_booking_id
         AND v_receipt.request_digest = p_request_digest THEN
        SELECT details_version INTO v_current_details_version
          FROM bookings WHERE id = v_receipt.booking_id;
        RETURN jsonb_build_object('outcome', 'idempotent',
          'booking_id', v_receipt.booking_id, 'details_version', v_current_details_version);
      END IF;
      INSERT INTO quote_verifications (verdict, mode, purpose, booking_id, identity_hash)
        VALUES (CASE
                  WHEN v_receipt.auth_user_id IS DISTINCT FROM p_auth_user_id
                    OR v_receipt.customer_id IS DISTINCT FROM p_customer_id
                  THEN 'replay_identity_mismatch'
                  ELSE 'replay_context_mismatch'
                END, v_mode, 'edit', p_booking_id, v_idhash);
      RETURN jsonb_build_object('outcome', 'conflict');
    END IF;
  END IF;
  IF NOT v_row_found OR v_row.customer_id IS DISTINCT FROM p_customer_id THEN
    RETURN jsonb_build_object('outcome', 'not_found');
  END IF;
  IF v_row.status <> 'pending' OR v_row.assigned_driver IS NOT NULL THEN
    INSERT INTO quote_verifications (verdict, mode, purpose, booking_id, identity_hash)
      VALUES ('edit_conflict', v_mode, 'edit', p_booking_id, v_idhash);
    RETURN jsonb_build_object('outcome', 'not_editable', 'status', v_row.status);
  END IF;
  IF v_row.details_version IS DISTINCT FROM p_expected_details_version THEN
    INSERT INTO quote_verifications (verdict, mode, purpose, booking_id, identity_hash)
      VALUES ('edit_conflict', v_mode, 'edit', p_booking_id, v_idhash);
    RETURN jsonb_build_object('outcome', 'version_conflict',
      'details_version', v_row.details_version);
  END IF;
  IF v_effective_verdict = 'verified' THEN
    -- Edit tokens bind bookingId + assignmentEpoch (plan v5 C12/C13):
    -- a token issued before an Accept/Release era cannot apply after.
    IF (p_payload->>'bookingId')::UUID IS DISTINCT FROM p_booking_id THEN
      INSERT INTO quote_verifications (
        verdict, mode, purpose, jti, token_digest, booking_id, identity_hash
      ) VALUES ('edit_conflict', v_mode, 'edit', p_jti, p_token_digest,
                p_booking_id, v_idhash);
      RETURN jsonb_build_object('outcome', 'quote_mismatch');
    END IF;
    IF (p_payload->>'assignmentEpoch')::INTEGER IS DISTINCT FROM v_row.assignment_epoch THEN
      INSERT INTO quote_verifications (
        verdict, mode, purpose, jti, token_digest, booking_id, identity_hash
      ) VALUES ('edit_conflict', v_mode, 'edit', p_jti, p_token_digest,
                p_booking_id, v_idhash);
      RETURN jsonb_build_object('outcome', 'epoch_conflict');
    END IF;
  END IF;

  -- Resolve the complete form against the locked row before the money/write
  -- phase. Missing/blank optional values preserve stored truth; customer
  -- name/phone cannot be cleared; a coherent booker pair is updated atomically.
  v_pickup_at := COALESCE(
    NULLIF(p_edit->>'pickup_datetime','')::TIMESTAMPTZ, v_row.pickup_datetime);
  v_passengers := COALESCE(NULLIF(p_edit->>'passengers','')::INTEGER, v_row.passengers);
  v_bags := COALESCE(NULLIF(p_edit->>'bags','')::INTEGER, v_row.bags);
  v_booking_mode := COALESCE(NULLIF(btrim(p_edit->>'booking_mode'),''), v_row.booking_mode);
  -- R1: no row fallback — the band check below must validate the SUBMITTED
  -- input only. Falling back to the stored value would turn it into
  -- stored-data validation and let a legacy out-of-band row fail an
  -- otherwise valid edit (verification finding, 2026-09-01).
  v_duration_minutes := NULLIF(p_edit->>'duration_minutes','')::INTEGER;
  v_customer_name := COALESCE(
    NULLIF(btrim(p_edit->>'customer_name'),''), v_row.customer_name);
  v_customer_phone := COALESCE(
    NULLIF(btrim(p_edit->>'customer_phone'),''), v_row.customer_phone);
  v_customer_email := COALESCE(
    NULLIF(btrim(p_edit->>'customer_email'),''), v_row.customer_email);
  v_payment_method := COALESCE(
    NULLIF(btrim(p_edit->>'payment_method'),''), v_row.payment_method, 'cash');

  IF p_edit ? 'booker_name' AND NULLIF(btrim(p_edit->>'booker_name'),'') IS NOT NULL THEN
    IF btrim(p_edit->>'booker_name') = v_customer_name THEN
      v_booker_name := NULL;
      v_booker_phone := NULL;
    ELSE
      v_booker_name := btrim(p_edit->>'booker_name');
      v_booker_phone := NULLIF(btrim(p_edit->>'booker_phone'),'');
    END IF;
  ELSE
    v_booker_name := v_row.booker_name;
    v_booker_phone := v_row.booker_phone;
  END IF;

  IF v_pickup_at IS NULL
     OR v_passengers IS NULL OR v_passengers < 1 OR v_passengers > 12
     OR v_bags IS NULL OR v_bags < 0 OR v_bags > 15
     OR v_booking_mode IS NULL OR v_booking_mode NOT IN ('pickup','dropoff')
     OR (v_duration_minutes IS NOT NULL
       AND (v_duration_minutes < 1 OR v_duration_minutes > 1440))

     OR NULLIF(btrim(v_customer_name),'') IS NULL
     OR NULLIF(btrim(v_customer_phone),'') IS NULL
     OR char_length(v_customer_name) > 120
     OR char_length(v_customer_phone) > 40
     OR (v_customer_email IS NOT NULL AND char_length(v_customer_email) > 254)
     OR (v_booker_name IS NOT NULL AND char_length(v_booker_name) > 120)
     OR (v_booker_phone IS NOT NULL AND char_length(v_booker_phone) > 40)
     OR char_length(v_payment_method) > 30 THEN
    RAISE EXCEPTION 'edit ride details are invalid';
  END IF;

  IF v_effective_verdict = 'verified' AND
     v_pickup_at IS DISTINCT FROM
       to_timestamp(((p_payload->>'pickupAtMs')::BIGINT) / 1000.0) THEN
    INSERT INTO quote_verifications (
      verdict, mode, purpose, jti, token_digest, booking_id, identity_hash
    ) VALUES ('edit_conflict', v_mode, 'edit', p_jti, p_token_digest,
              p_booking_id, v_idhash);
    RETURN jsonb_build_object('outcome', 'quote_mismatch');
  END IF;

  IF v_mode = 'enforce' THEN
    v_cents := (p_payload->>'finalCents')::INTEGER;
    v_price := v_cents / 100.0;
    v_authority := 'server_quote';
  ELSIF v_mode = 'observe' THEN
    IF p_client_price IS NULL THEN
      RAISE EXCEPTION 'off/observe modes require a safe client price';
    END IF;
    v_price := round(p_client_price * 100) / 100.0;
    v_cents := round(p_client_price * 100)::INTEGER;
    v_authority := 'client_observe';
  ELSE
    IF p_client_price IS NULL THEN
      RAISE EXCEPTION 'off/observe modes require a safe client price';
    END IF;
    v_price := round(p_client_price * 100) / 100.0;
    v_cents := round(p_client_price * 100)::INTEGER;
    v_authority := 'client_legacy';
  END IF;

  IF v_row.referred_by_host IS NOT NULL THEN
    IF v_row.price > 0 THEN
      v_commission_rate := COALESCE(v_row.host_commission, 0) / v_row.price;
    ELSIF COALESCE(v_row.host_commission, 0) = 0 THEN
      v_commission_rate := 0;
    ELSE
      RAISE EXCEPTION 'stored ambassador commission ratio is invalid';
    END IF;
    IF v_commission_rate < 0 OR v_commission_rate > 1 THEN
      RAISE EXCEPTION 'stored ambassador commission ratio is invalid';
    END IF;
  END IF;
  v_host_commission := round(v_price * v_commission_rate, 2);

  -- PR-T pre-mutation pickup guard: transaction-stable clock, OUTSIDE every
  -- verified-only branch (all three verdicts obey it). An elapsed pickup
  -- returns before any business write; the guard itself records nothing.
  -- Pre-existing and deliberately NOT moved: the edit writer's inherited
  -- 017 telemetry row for an operationId-less caller in off/observe
  -- ('no_request_id', written ABOVE this guard, outside the subtransaction)
  -- is the one row such a legacy caller still leaves — pinned by the
  -- executed suite. The browser always sends an operationId.
  IF NOT public.linkmia_pickup_is_future(v_pickup_at, transaction_timestamp()) THEN
    RETURN jsonb_build_object('outcome', 'pickup_time_elapsed');
  END IF;

  PERFORM set_config('linkmia.rpc_writer', 'on', TRUE);
  BEGIN
    UPDATE bookings SET
      pickup_location = COALESCE(p_edit->>'pickup_location', pickup_location),
      dropoff_location = COALESCE(p_edit->>'dropoff_location', dropoff_location),
      pickup_datetime = v_pickup_at,
      passengers = v_passengers,
      bags = v_bags,
      vehicle_type = CASE WHEN p_verdict = 'verified' THEN CASE p_vehicle_key
        WHEN 'tesla' THEN 'sedan' WHEN 'escalade' THEN 'suv'
        WHEN 'sprinter' THEN 'sprinter' END
        ELSE COALESCE(p_edit->>'vehicle_type', vehicle_type) END,
      vehicle_name = CASE WHEN p_verdict = 'verified' THEN CASE p_vehicle_key
        WHEN 'tesla' THEN 'Tesla Model Y'
        WHEN 'escalade' THEN 'Cadillac Escalade'
        WHEN 'sprinter' THEN 'Mercedes Sprinter' END
        ELSE COALESCE(p_edit->>'vehicle_name', vehicle_name) END,
      booking_mode = v_booking_mode,
      -- R1: provider duration is never persisted; an edit is a new write,
      -- so it also clears any legacy stored value on the row it touches.
      duration_minutes = NULL,
      customer_name = v_customer_name,
      customer_phone = v_customer_phone,
      customer_email = v_customer_email,
      booker_name = v_booker_name,
      booker_phone = v_booker_phone,
      payment_method = v_payment_method,
      flight_number = COALESCE(NULLIF(p_edit->>'flight_number',''), flight_number),
      notes = COALESCE(NULLIF(p_edit->>'notes',''), notes),
      pickup_sign = COALESCE(NULLIF(p_edit->>'pickup_sign',''), pickup_sign),
      promo_code = COALESCE(NULLIF(p_edit->>'promo_code',''), promo_code),
      host_commission = v_host_commission,
      price = v_price,
      price_cents = v_cents,
      price_authority = v_authority,
      -- A full-form edit changes the ride intent.  If the replacement intent
      -- was not verified, retaining the old canonical identity would falsely
      -- claim that it still described the edited route.  Downgrade honestly.
      canonical_place_id = CASE WHEN v_effective_verdict = 'verified' AND v_mode <> 'off'
        THEN p_canonical_place_id ELSE NULL END,
      airport_code = CASE WHEN v_effective_verdict = 'verified' AND v_mode <> 'off'
        THEN p_airport_code ELSE NULL END,
      route_authority = CASE WHEN v_effective_verdict = 'verified' AND v_mode <> 'off'
        THEN 'canonical' ELSE 'legacy_text' END,
      details_version = details_version + 1,
      updated_at = now()
    WHERE id = p_booking_id;

    IF v_effective_verdict = 'verified' THEN
      INSERT INTO quote_acceptances (
        jti, token_digest, booking_id, purpose, auth_user_id, customer_id,
        kid, vehicle_key, final_cents, client_cents, authority,
        pricing_version, engine_version, resolved_version,
        canonical_place_id, airport_code, booking_mode, pickup_at, passengers,
        payload_projection
      ) VALUES (
        p_jti, p_token_digest, p_booking_id, 'edit', p_auth_user_id, p_customer_id,
        p_payload->>'kid', p_vehicle_key, (p_payload->>'finalCents')::INTEGER,
        CASE WHEN v_mode <> 'enforce' THEN v_cents ELSE NULL END,
        v_authority,
        p_payload->>'pricingVersion', p_payload->>'engineVersion', p_payload->>'resolvedVersion',
        p_canonical_place_id, p_airport_code,
        v_booking_mode,
        to_timestamp(((p_payload->>'pickupAtMs')::BIGINT) / 1000.0),
        v_passengers,
        -- R1 fail-closed acceptance projection: an explicit ALLOWLIST of the
        -- token's non-provider fields. routeQuality (Google Routes
        -- fallbackInfo) is excluded, and any future token field stays out
        -- until it is named here. Distance/duration exist only inside the
        -- keyed commitment hash and were never plaintext.
        jsonb_build_object(
          'v', p_payload->'v',
          'kid', p_payload->'kid',
          'jti', p_payload->'jti',
          'purpose', p_payload->'purpose',
          'authUserId', p_payload->'authUserId',
          'customerId', p_payload->'customerId',
          'bookingId', p_payload->'bookingId',
          'assignmentEpoch', p_payload->'assignmentEpoch',
          'vehicle', p_payload->'vehicle',
          'pickupAtMs', p_payload->'pickupAtMs',
          'commitment', p_payload->'commitment',
          'finalCents', p_payload->'finalCents',
          'pricingVersion', p_payload->'pricingVersion',
          'engineVersion', p_payload->'engineVersion',
          'resolvedVersion', p_payload->'resolvedVersion',
          'iat', p_payload->'iat',
          'exp', p_payload->'exp'
        )
      );
    END IF;

    IF v_has_request_id THEN
      INSERT INTO operation_receipts (
        operation_request_id, kind, auth_user_id, customer_id,
        request_digest, booking_id, details_version
      ) VALUES (
        p_operation_request_id, 'edit_quoted', p_auth_user_id, p_customer_id,
        p_request_digest, p_booking_id, v_row.details_version + 1
      );
    END IF;

    -- Acceptance/receipt uniqueness can block after the post-row-lock clock
    -- check. Roll back the edit and all acceptance/receipt writes if the price
    -- hold expires during that final wait.
    IF p_verdict = 'verified' THEN
      v_now_ms := floor(extract(epoch FROM clock_timestamp()) * 1000)::BIGINT;
      IF (p_payload->>'iat')::BIGINT > v_now_ms + 60000 THEN
        v_effective_verdict := 'not_yet_valid';
      ELSIF v_now_ms >= (p_payload->>'exp')::BIGINT THEN
        v_effective_verdict := 'expired';
      END IF;
      IF v_effective_verdict <> 'verified' THEN
        RAISE EXCEPTION USING ERRCODE = 'ZQ017', MESSAGE = v_effective_verdict;
      END IF;
    END IF;

    INSERT INTO quote_verifications (
      verdict, mode, purpose, jti, token_digest, booking_id, identity_hash,
      client_cents, server_cents
    ) VALUES (
      v_effective_verdict,
      v_mode, 'edit',
      CASE WHEN v_effective_verdict = 'verified' THEN p_jti ELSE NULL END,
      CASE WHEN v_effective_verdict = 'verified' THEN p_token_digest ELSE NULL END,
      p_booking_id, v_idhash,
      CASE WHEN p_client_price IS NOT NULL THEN round(p_client_price * 100)::INTEGER ELSE NULL END,
      CASE WHEN p_verdict = 'verified' THEN (p_payload->>'finalCents')::INTEGER ELSE NULL END
    );

    -- PR-T final pickup guard: the LAST potentially blocking statement in
    -- this subtransaction — AFTER the telemetry insert, on the live clock.
    -- A pickup that elapsed during any lock wait rolls every write back.
    IF NOT public.linkmia_pickup_is_future(v_pickup_at, clock_timestamp()) THEN
      RAISE EXCEPTION USING ERRCODE = 'ZQ019', MESSAGE = 'pickup_time_elapsed';
    END IF;
    PERFORM set_config('linkmia.rpc_writer', 'off', TRUE);
    RETURN jsonb_build_object('outcome', 'updated', 'booking_id', p_booking_id,
      'details_version', v_row.details_version + 1, 'authority', v_authority);

  EXCEPTION WHEN SQLSTATE 'ZQ017' THEN
    PERFORM set_config('linkmia.rpc_writer', 'off', TRUE);
    INSERT INTO quote_verifications (
      verdict, mode, purpose, jti, token_digest, booking_id, identity_hash
    ) VALUES (v_effective_verdict, v_mode, 'edit', p_jti, p_token_digest,
              p_booking_id, v_idhash);
    RETURN jsonb_build_object('outcome', CASE
      WHEN v_effective_verdict = 'expired' THEN 'quote_expired'
      ELSE 'quote_not_yet_valid' END);

  WHEN SQLSTATE 'ZQ019' THEN
    -- PR-T: every booking/acceptance/receipt/telemetry write INSIDE the
    -- subtransaction rolled back with it. No verdict row is written by the
    -- guard (the closed verdict CHECK is untouched) and v_effective_verdict
    -- is never changed. A telemetry row written BEFORE the block (the edit
    -- writer's operationId-less 'no_request_id' instrument) is outside it
    -- and survives, exactly as it did before PR-T.
    PERFORM set_config('linkmia.rpc_writer', 'off', TRUE);
    RETURN jsonb_build_object('outcome', 'pickup_time_elapsed');

  WHEN unique_violation THEN
    PERFORM set_config('linkmia.rpc_writer', 'off', TRUE);
    GET STACKED DIAGNOSTICS v_constraint = CONSTRAINT_NAME;
    -- The block above rolled back, its telemetry included: the losing
    -- attempt's evidence is written HERE, where it commits (mirrors
    -- the create RPC's handler).
    IF v_constraint IN ('quote_acceptances_jti_key', 'quote_acceptances_token_digest_key') THEN
      SELECT * INTO v_accept FROM quote_acceptances
        WHERE jti = p_jti OR token_digest = p_token_digest
        ORDER BY (token_digest = p_token_digest) DESC LIMIT 1;
      IF FOUND AND v_accept.auth_user_id = p_auth_user_id
               AND v_accept.customer_id = p_customer_id
               AND v_accept.purpose = 'edit'
               AND v_accept.booking_id = p_booking_id THEN
        IF v_accept.token_digest = p_token_digest THEN
          SELECT details_version INTO v_current_details_version
            FROM bookings WHERE id = v_accept.booking_id;
          INSERT INTO quote_verifications (verdict, mode, purpose, jti, token_digest, booking_id, identity_hash)
            VALUES ('replay_idempotent', v_mode, 'edit', p_jti, p_token_digest, v_accept.booking_id, v_idhash);
          RETURN jsonb_build_object('outcome', 'idempotent',
            'booking_id', v_accept.booking_id,
            'details_version', v_current_details_version);
        END IF;
        INSERT INTO quote_verifications (verdict, mode, purpose, jti, booking_id, identity_hash)
          VALUES ('quote_consumed', v_mode, 'edit', p_jti, v_accept.booking_id, v_idhash);
        RETURN jsonb_build_object('outcome', 'quote_consumed', 'booking_id', v_accept.booking_id);
      END IF;
      INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
        VALUES (CASE
                  WHEN FOUND AND v_accept.auth_user_id = p_auth_user_id
                    AND v_accept.customer_id = p_customer_id
                  THEN 'replay_context_mismatch'
                  ELSE 'replay_identity_mismatch'
                END, v_mode, 'edit', v_idhash);
      RETURN jsonb_build_object('outcome', 'refused');
    ELSIF v_constraint = 'operation_receipts_operation_request_id_key' THEN
      SELECT * INTO v_receipt FROM operation_receipts
        WHERE operation_request_id = p_operation_request_id;
      IF FOUND AND v_receipt.auth_user_id = p_auth_user_id
               AND v_receipt.customer_id = p_customer_id
               AND v_receipt.kind = 'edit_quoted'
               AND v_receipt.booking_id = p_booking_id
               AND v_receipt.request_digest = p_request_digest THEN
        SELECT details_version INTO v_current_details_version
          FROM bookings WHERE id = v_receipt.booking_id;
        RETURN jsonb_build_object('outcome', 'idempotent',
          'booking_id', v_receipt.booking_id, 'details_version', v_current_details_version);
      END IF;
      INSERT INTO quote_verifications (verdict, mode, purpose, identity_hash)
        VALUES (CASE
                  WHEN FOUND AND (v_receipt.auth_user_id IS DISTINCT FROM p_auth_user_id
                    OR v_receipt.customer_id IS DISTINCT FROM p_customer_id)
                  THEN 'replay_identity_mismatch'
                  ELSE 'replay_context_mismatch'
                END, v_mode, 'edit', v_idhash);
      RETURN jsonb_build_object('outcome', 'conflict');
    END IF;
    RAISE;
  END;
END $$;

-- ------------------------------------------------------------
-- Self-verification (017/018 discipline): raise = whole transaction aborts.
-- ------------------------------------------------------------
DO $prt_verify$
DECLARE
  v_def TEXT;
  v_row RECORD;
  v_helper pg_proc%ROWTYPE;
  v_expected_grantees OID[];
  v_actual_grantees OID[];
BEGIN
  IF (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'public' AND p.proname = 'accept_quote_create') <> 1
     OR (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'public' AND p.proname = 'accept_quote_edit') <> 1 THEN
    RAISE EXCEPTION 'PR-T: overload detected — replacement must not add a signature';
  END IF;
  -- Helper: exactly one signature, IMMUTABLE, STRICT, security INVOKER,
  -- owned by the captured writer owner, every client role denied — and still
  -- callable by the writers (owner privilege), verified behaviorally.
  IF (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'public' AND p.proname = 'linkmia_pickup_is_future') <> 1 THEN
    RAISE EXCEPTION 'PR-T: helper must have exactly one signature';
  END IF;
  SELECT p.* INTO v_helper FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'linkmia_pickup_is_future';
  IF v_helper.provolatile <> 'i' OR NOT v_helper.proisstrict OR v_helper.prosecdef THEN
    RAISE EXCEPTION 'PR-T: helper must be IMMUTABLE STRICT and security invoker';
  END IF;
  IF v_helper.proowner <> (SELECT proowner FROM prt_pre_state WHERE proname = 'accept_quote_create') THEN
    RAISE EXCEPTION 'PR-T: helper owner must be the captured writer owner';
  END IF;
  IF has_function_privilege('anon', v_helper.oid, 'EXECUTE')
     OR has_function_privilege('authenticated', v_helper.oid, 'EXECUTE')
     OR has_function_privilege('service_role', v_helper.oid, 'EXECUTE') THEN
    RAISE EXCEPTION 'PR-T: a client or service role can execute the helper';
  END IF;
  -- EXACT ACL: the EXECUTE grantee set equals the captured writer owner set —
  -- nothing more (PUBLIC included), nothing less. A NULL ACL means defaults
  -- (PUBLIC executes) and fails.
  SELECT array_agg(DISTINCT proowner ORDER BY proowner) INTO v_expected_grantees FROM prt_pre_state;
  SELECT array_agg(DISTINCT (x.a).grantee ORDER BY (x.a).grantee) INTO v_actual_grantees
    FROM (SELECT aclexplode(v_helper.proacl) AS a) x
    WHERE (x.a).privilege_type = 'EXECUTE';
  IF v_helper.proacl IS NULL OR v_actual_grantees IS DISTINCT FROM v_expected_grantees THEN
    RAISE EXCEPTION 'PR-T: helper EXECUTE grantees % are not exactly the captured writer owners %',
      v_actual_grantees, v_expected_grantees;
  END IF;
  IF NOT public.linkmia_pickup_is_future(now() + interval '1 microsecond', now())
     OR public.linkmia_pickup_is_future(now(), now()) THEN
    RAISE EXCEPTION 'PR-T: helper boundary is wrong (strictly-later must pass, exact-now must refuse)';
  END IF;

  FOR v_row IN SELECT * FROM prt_pre_state LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE p.oid = v_row.oid AND n.nspname = 'public'
        AND p.proname = v_row.proname
        AND p.proowner = v_row.proowner
        AND p.proacl IS NOT DISTINCT FROM v_row.proacl
        AND p.proconfig IS NOT DISTINCT FROM v_row.proconfig
    ) THEN
      RAISE EXCEPTION 'PR-T: identity/owner/ACL/config drifted for % during replacement', v_row.proname;
    END IF;
    IF NOT (SELECT prosecdef FROM pg_proc WHERE oid = v_row.oid) THEN
      RAISE EXCEPTION 'PR-T: SECURITY DEFINER was lost on %', v_row.proname;
    END IF;
    -- The installed body after replacement must be EXACTLY this artifact's
    -- generated body (an altered or partial paste cannot commit).
    -- (the CASE is parenthesized: PL/pgSQL ends an IF condition at the first
    --  unparenthesized THEN)
    IF encode(extensions.digest((SELECT prosrc FROM pg_proc WHERE oid = v_row.oid), 'sha256'), 'hex')
       <> (CASE v_row.proname WHEN 'accept_quote_create' THEN 'fc64b32ca907098b8ccceb5c912fa9d290a5e9c14a4f0704013d6b226f506396' ELSE 'ce81f347112d3cd251738d9bece093154ea27cccd09b6a2c8ea0e21f75a6e50d' END) THEN
      RAISE EXCEPTION 'PR-T: the installed % body after replacement is not this artifact''s generated body (altered paste?)', v_row.proname;
    END IF;
    IF v_row.proconfig IS NULL OR array_to_string(v_row.proconfig, ',') NOT LIKE '%search_path%' THEN
      RAISE EXCEPTION 'PR-T: SET search_path drifted on %', v_row.proname;
    END IF;
    IF NOT has_function_privilege('service_role', v_row.oid, 'EXECUTE') THEN
      RAISE EXCEPTION 'PR-T: service_role lost EXECUTE on %', v_row.proname;
    END IF;
    IF has_function_privilege('anon', v_row.oid, 'EXECUTE')
       OR has_function_privilege('authenticated', v_row.oid, 'EXECUTE') THEN
      RAISE EXCEPTION 'PR-T: client role gained EXECUTE on %', v_row.proname;
    END IF;

    v_def := pg_get_functiondef(v_row.oid);
    -- Both guards present on the right clocks, in SEQUENCE: LIKE proves the
    -- pre-mutation guard precedes rpc_writer 'on', and that the final guard
    -- is followed by ERRCODE ZQ019, set_config 'off' and the RETURN. This is
    -- a presence/sequence TRIPWIRE, not the order authority: "some telemetry
    -- INSERT precedes the final guard" is satisfied by any earlier insert.
    -- The EXACT order (final guard after the LAST success-path telemetry
    -- insert) is pinned by the executed suite's STATEMENT ORDER row, which
    -- compares positions in both artifacts.
    IF v_def NOT LIKE '%linkmia_pickup_is_future(v_pickup_at, transaction_timestamp())%rpc_writer'', ''on''%' THEN
      RAISE EXCEPTION 'PR-T: pre-mutation pickup guard missing or misplaced in %', v_row.proname;
    END IF;
    IF v_def NOT LIKE '%INSERT INTO quote_verifications%linkmia_pickup_is_future(v_pickup_at, clock_timestamp())%ERRCODE = ''ZQ019''%rpc_writer'', ''off''%RETURN jsonb_build_object(''outcome'', ''%' THEN
      RAISE EXCEPTION 'PR-T: final pickup guard missing or not the last blocking statement in %', v_row.proname;
    END IF;
    IF v_def NOT LIKE '%WHEN SQLSTATE ''ZQ019'' THEN%''pickup_time_elapsed''%' THEN
      RAISE EXCEPTION 'PR-T: dedicated ZQ019 handler missing in %', v_row.proname;
    END IF;
    IF v_def LIKE '%v_effective_verdict := ''pickup_time_elapsed''%' THEN
      RAISE EXCEPTION 'PR-T: pickup_time_elapsed must never become a verdict in %', v_row.proname;
    END IF;
    -- 018 semantics must still hold: no persisted duration.
    IF v_row.proname = 'accept_quote_create' AND v_def NOT LIKE '%NULL::INTEGER%' THEN
      RAISE EXCEPTION 'PR-T: the create insert persists a duration again';
    END IF;
    IF v_row.proname = 'accept_quote_edit' AND v_def NOT LIKE '%duration_minutes = NULL%' THEN
      RAISE EXCEPTION 'PR-T: the edit update persists a duration again';
    END IF;
  END LOOP;
END;
$prt_verify$;

-- ------------------------------------------------------------
-- ROLLBACK-CONTAINED BEHAVIORAL SMOKE (017/018 discipline, sentinel ZZ019):
-- a no-token create with an ELAPSED pickup answers pickup_time_elapsed and
-- writes nothing; a future create succeeds; an edit of that booking with an
-- elapsed proposed pickup answers pickup_time_elapsed; a future edit
-- succeeds. Then forced rollback and a row-count residue proof. Sequence
-- values consumed are deliberately not rewound (018 precedent).
-- ------------------------------------------------------------
DO $prt_smoke$
DECLARE
  v_bookings_before BIGINT;
  v_customers_before BIGINT;
  v_accept_before BIGINT;
  v_verify_before BIGINT;
  v_receipts_before BIGINT;
  v_customer UUID;
  v_auth UUID := gen_random_uuid();
  v_booking UUID;
  v_op1 UUID := gen_random_uuid();
  v_op2 UUID := gen_random_uuid();
  v_op3 UUID := gen_random_uuid();
  v_op4 UUID := gen_random_uuid();
  v_result JSONB;
  v_future TEXT := (clock_timestamp() + interval '1 day')::TEXT;
  v_past TEXT := (clock_timestamp() - interval '1 minute')::TEXT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pricing_state WHERE singleton AND mode IN ('off','observe')) THEN
    RAISE EXCEPTION 'PR-T smoke requires pricing mode off or observe — runbook STOP applies';
  END IF;
  SELECT count(*) INTO v_bookings_before FROM bookings;
  SELECT count(*) INTO v_customers_before FROM customers;
  SELECT count(*) INTO v_accept_before FROM quote_acceptances;
  SELECT count(*) INTO v_verify_before FROM quote_verifications;
  SELECT count(*) INTO v_receipts_before FROM operation_receipts;

  BEGIN
    INSERT INTO customers (name, phone, email, type, source)
      VALUES ('MIGRATION-019-PRT-SMOKE','0000000019','prtsmoke@example.invalid','guest','website')
      RETURNING id INTO v_customer;

    -- 1. elapsed pickup -> refused before any write
    v_result := accept_quote_create(
      v_auth, v_customer, v_op1, encode(extensions.digest(v_op1::text, 'sha256'), 'hex'),
      'no_token', NULL, NULL, NULL, 40.00, NULL, NULL, NULL,
      jsonb_build_object('trip_id','MIG019-PAST','customer_name','MIGRATION-019-PRT-SMOKE',
        'customer_phone','0000000019','pickup_location','prt-smoke-origin',
        'dropoff_location','prt-smoke-destination','pickup_datetime',v_past,
        'passengers',1,'bags',0,'vehicle_type','sedan','vehicle_name','Tesla Model Y',
        'booking_mode','dropoff','source','website'));
    IF v_result->>'outcome' IS DISTINCT FROM 'pickup_time_elapsed' THEN
      RAISE EXCEPTION 'PR-T smoke: elapsed create was not refused: %', v_result;
    END IF;
    IF (SELECT count(*) FROM bookings) <> v_bookings_before
       OR (SELECT count(*) FROM operation_receipts) <> v_receipts_before
       OR (SELECT count(*) FROM quote_verifications) <> v_verify_before THEN
      RAISE EXCEPTION 'PR-T smoke: an elapsed create wrote something';
    END IF;

    -- 2. future pickup -> created
    v_result := accept_quote_create(
      v_auth, v_customer, v_op2, encode(extensions.digest(v_op2::text, 'sha256'), 'hex'),
      'no_token', NULL, NULL, NULL, 40.00, NULL, NULL, NULL,
      jsonb_build_object('trip_id','MIG019-FUTURE','customer_name','MIGRATION-019-PRT-SMOKE',
        'customer_phone','0000000019','pickup_location','prt-smoke-origin',
        'dropoff_location','prt-smoke-destination','pickup_datetime',v_future,
        'passengers',1,'bags',0,'vehicle_type','sedan','vehicle_name','Tesla Model Y',
        'booking_mode','dropoff','source','website'));
    IF v_result->>'outcome' IS DISTINCT FROM 'created' THEN
      RAISE EXCEPTION 'PR-T smoke: future create failed: %', v_result;
    END IF;
    v_booking := (v_result->>'booking_id')::UUID;

    -- 3. edit proposing an elapsed pickup -> refused, row untouched
    v_result := accept_quote_edit(
      v_auth, v_customer, v_op3, encode(extensions.digest(v_op3::text, 'sha256'), 'hex'),
      v_booking, 1, 'no_token', NULL, NULL, NULL, 41.00, NULL, NULL, NULL,
      jsonb_build_object('pickup_datetime', v_past));
    IF v_result->>'outcome' IS DISTINCT FROM 'pickup_time_elapsed' THEN
      RAISE EXCEPTION 'PR-T smoke: elapsed edit was not refused: %', v_result;
    END IF;
    IF (SELECT details_version FROM bookings WHERE id = v_booking) <> 1 THEN
      RAISE EXCEPTION 'PR-T smoke: an elapsed edit changed the row';
    END IF;

    -- 4. edit proposing a future pickup -> updated
    v_result := accept_quote_edit(
      v_auth, v_customer, v_op4, encode(extensions.digest(v_op4::text, 'sha256'), 'hex'),
      v_booking, 1, 'no_token', NULL, NULL, NULL, 41.00, NULL, NULL, NULL,
      jsonb_build_object('pickup_datetime', (clock_timestamp() + interval '2 days')::TEXT));
    IF v_result->>'outcome' IS DISTINCT FROM 'updated' THEN
      RAISE EXCEPTION 'PR-T smoke: future edit failed: %', v_result;
    END IF;

    RAISE EXCEPTION USING ERRCODE = 'ZZ019', MESSAGE = 'MIGRATION_019_PRT_SMOKE_ROLLBACK';
  EXCEPTION WHEN SQLSTATE 'ZZ019' THEN
    IF SQLERRM <> 'MIGRATION_019_PRT_SMOKE_ROLLBACK' THEN RAISE; END IF;
  END;

  IF (SELECT count(*) FROM bookings) <> v_bookings_before
     OR (SELECT count(*) FROM customers) <> v_customers_before
     OR (SELECT count(*) FROM quote_acceptances) <> v_accept_before
     OR (SELECT count(*) FROM quote_verifications) <> v_verify_before
     OR (SELECT count(*) FROM operation_receipts) <> v_receipts_before THEN
    RAISE EXCEPTION 'PR-T smoke residue: rollback-contained smoke changed row counts';
  END IF;
END;
$prt_smoke$;

COMMIT;
