-- ============================================================
-- Migration 019 (PR-T) — READ-ONLY production preflight
-- ============================================================
-- Run BEFORE pasting 019_prt_pickup_time_integrity.sql. It changes nothing.
-- Preserve every result grid as rollout evidence and STOP if any stated gate
-- fails. Supabase SQL Editor shows only the last grid of a multi-statement
-- run: execute each labeled check separately. Every check is its own
-- BEGIN; SET TRANSACTION READ ONLY; one grid; ROLLBACK unit.
--
-- Procedure, not authorization: docs/PRT-MIGRATION-RUNBOOK.md.

BEGIN;
SET TRANSACTION READ ONLY;

-- A1. Exactly the two public writers, namespace-qualified, with the installed
--     018 identities: SECURITY DEFINER, search_path set, service_role EXECUTE
--     held, client roles barred. Expect 2 rows, prosecdef=true, sr_exec=true,
--     anon_exec=false, auth_exec=false, and search_path present in proconfig.
SELECT n.nspname, p.proname, p.oid::regprocedure AS signature,
       pg_get_userbyid(p.proowner) AS owner, p.prosecdef, p.proconfig,
       has_function_privilege('service_role', p.oid, 'EXECUTE') AS sr_exec,
       has_function_privilege('anon', p.oid, 'EXECUTE') AS anon_exec,
       has_function_privilege('authenticated', p.oid, 'EXECUTE') AS auth_exec
FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'public'
  AND p.proname IN ('accept_quote_create', 'accept_quote_edit')
ORDER BY p.proname;
ROLLBACK;

BEGIN;
SET TRANSACTION READ ONLY;
-- A2. The installed bodies are EXACTLY a recognized reviewed 018 PAIR
--     (fingerprint = sha256(pg_proc.prosrc), the same values migration 019's
--     pre-capture requires) and carry NO pickup guard yet. installed_pair is
--     computed over BOTH writers at once and is the same on both rows. Expect
--     installed_pair IN ('reviewed_018', 'reviewed_018_as_pasted_2026_09_01')
--     and guarded=false. 'reviewed_018_as_pasted_2026_09_01' is the reviewed
--     018 code as production received it (comment punctuation re-encoded by
--     the paste channel; derivation named and pinned). ANY other value -
--     'UNRECOGNIZED_OR_MIXED' - means an unreviewed change or a mixed state is
--     installed: STOP (019 would refuse it too). The expressions between the
--     markers are GENERATED by prt-guard-transform.js --write and verified by
--     --check and the executed suite - never hand-edit them.
SELECT p.proname,
       encode(extensions.digest(p.prosrc, 'sha256'), 'hex') AS body_sha256,
-- PRT-EXPECTED-FINGERPRINTS:BEGIN (generated — do not hand-edit)
       CASE
         WHEN (SELECT encode(extensions.digest(prosrc, 'sha256'), 'hex') FROM pg_proc WHERE oid = 'public.accept_quote_create(uuid,uuid,uuid,text,text,uuid,text,jsonb,numeric,text,text,text,jsonb)'::regprocedure) = 'ed86cca5e4f5046dc9503771a38bb63f7b4140956dfb94b645f076cd59483388' AND (SELECT encode(extensions.digest(prosrc, 'sha256'), 'hex') FROM pg_proc WHERE oid = 'public.accept_quote_edit(uuid,uuid,uuid,text,uuid,integer,text,uuid,text,jsonb,numeric,text,text,text,jsonb)'::regprocedure) = 'cc56cc673236db967d738209c9f9d5423e0e7117a74358e48280c08f0cd14b41' THEN 'reviewed_018'
         WHEN (SELECT encode(extensions.digest(prosrc, 'sha256'), 'hex') FROM pg_proc WHERE oid = 'public.accept_quote_create(uuid,uuid,uuid,text,text,uuid,text,jsonb,numeric,text,text,text,jsonb)'::regprocedure) = '3bb8663d8a052c02512538f3beb147740ae956e41c5f757a01c85b65c7cb85b6' AND (SELECT encode(extensions.digest(prosrc, 'sha256'), 'hex') FROM pg_proc WHERE oid = 'public.accept_quote_edit(uuid,uuid,uuid,text,uuid,integer,text,uuid,text,jsonb,numeric,text,text,text,jsonb)'::regprocedure) = '07fdcd2d564c6fbdf043b0b0d6f17ff67c8b3f3736153217e034a329822c1c81' THEN 'reviewed_018_as_pasted_2026_09_01'
         WHEN (SELECT encode(extensions.digest(prosrc, 'sha256'), 'hex') FROM pg_proc WHERE oid = 'public.accept_quote_create(uuid,uuid,uuid,text,text,uuid,text,jsonb,numeric,text,text,text,jsonb)'::regprocedure) = 'bed377560252619862bcad768a2d5615496aca0f3d5016c4731d5afad651b6e1' AND (SELECT encode(extensions.digest(prosrc, 'sha256'), 'hex') FROM pg_proc WHERE oid = 'public.accept_quote_edit(uuid,uuid,uuid,text,uuid,integer,text,uuid,text,jsonb,numeric,text,text,text,jsonb)'::regprocedure) = '0acb70791a784c9569ab062dba2c04e17be380f9e0a9ed28361f1f5dea2d5ed8' THEN 'target_019'
         WHEN (SELECT encode(extensions.digest(prosrc, 'sha256'), 'hex') FROM pg_proc WHERE oid = 'public.accept_quote_create(uuid,uuid,uuid,text,text,uuid,text,jsonb,numeric,text,text,text,jsonb)'::regprocedure) = 'f4f86e63f7b782e2206dc48468be738a7ba54077b5a450107fe176d362058f3e' AND (SELECT encode(extensions.digest(prosrc, 'sha256'), 'hex') FROM pg_proc WHERE oid = 'public.accept_quote_edit(uuid,uuid,uuid,text,uuid,integer,text,uuid,text,jsonb,numeric,text,text,text,jsonb)'::regprocedure) = '373edeb895dafcc7f06894915504829caaba5b9b47366df2f8b07aa804e364f0' THEN 'rollback'
         ELSE 'UNRECOGNIZED_OR_MIXED' END AS installed_pair,
-- PRT-EXPECTED-FINGERPRINTS:END
       (pg_get_functiondef(p.oid) LIKE '%linkmia_pickup_is_future%') AS guarded
FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'public' AND p.proname IN ('accept_quote_create', 'accept_quote_edit')
ORDER BY p.proname;
ROLLBACK;

BEGIN;
SET TRANSACTION READ ONLY;
-- A3. The helper must NOT exist yet (019 creates it). Expect 0.
SELECT count(*) AS helper_signatures
FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'public' AND p.proname = 'linkmia_pickup_is_future';
ROLLBACK;

BEGIN;
SET TRANSACTION READ ONLY;
-- B1. Pricing state: mode 'observe' (or 'off') with NO enforcement high-water
--     mark. Expect mode IN ('off','observe') and enforcement_started_at NULL.
--     Any other combination: STOP — this runbook assumes pre-enforcement.
SELECT mode, enforcement_started_at, updated_at FROM pricing_state WHERE singleton;
ROLLBACK;

BEGIN;
SET TRANSACTION READ ONLY;
-- B2. The telemetry verdict CHECK is the closed 017 list (019 must not widen
--     it; an elapsed refusal writes no verdict row). Exactly ONE row: the named
--     CHECK constraint on public.quote_verifications (any NOT NULL constraint
--     row is deliberately excluded). Expect verdict_literals=16, widened=false.
SELECT c.conname,
       (SELECT count(*) FROM regexp_matches(pg_get_constraintdef(c.oid), '''[a-z_]+''', 'g')) AS verdict_literals,
       pg_get_constraintdef(c.oid) LIKE '%pickup_time_elapsed%' AS widened
FROM pg_constraint c
WHERE c.conrelid = 'public.quote_verifications'::regclass
  AND c.contype = 'c'
  AND c.conname = 'quote_verifications_verdict_check';
ROLLBACK;

BEGIN;
SET TRANSACTION READ ONLY;
-- C1. Activity snapshot (evidence, not a lock — 019 takes no NOWAIT table
--     locks; it replaces two functions and runs a rollback-contained smoke).
--     Record nonterminal bookings and any in-flight writer transactions.
SELECT
  (SELECT count(*) FROM bookings WHERE status NOT IN ('completed','cancelled','declined')) AS nonterminal_bookings,
  (SELECT count(*) FROM bookings WHERE status NOT IN ('completed','cancelled','declined')
     AND pickup_datetime < now()) AS nonterminal_with_elapsed_pickup,
  (SELECT count(*) FROM pg_stat_activity
     WHERE state <> 'idle' AND query ILIKE '%accept_quote_%' AND pid <> pg_backend_pid()) AS writer_calls_in_flight,
  now() AS snapshot_at;
ROLLBACK;

BEGIN;
SET TRANSACTION READ ONLY;
-- C2. The row counts the migration's smoke will prove unchanged. Record them.
SELECT
  (SELECT count(*) FROM bookings) AS bookings,
  (SELECT count(*) FROM customers) AS customers,
  (SELECT count(*) FROM quote_acceptances) AS quote_acceptances,
  (SELECT count(*) FROM quote_verifications) AS quote_verifications,
  (SELECT count(*) FROM operation_receipts) AS operation_receipts;
ROLLBACK;
